import type { PlayTimeline } from './types'

/**
 * P90X Cardio X authored play timeline — transcribed verbatim from
 * docs/requirements/cardio-x.md (the oracle). Order = play order.
 *
 * Locked decisions (see E18 spec §1 + §4):
 * - Sun Salutation Vinyasas 1–2 are multi-pose flows → `seconds: null`, no
 *   `reps`, the chain verbatim in `cue`. They share `exerciseId:
 *   'sun-salutation-vinyasa'` and run contiguous ("Continuous flow") so the
 *   second is a seamless continuation (no get-ready gap between them).
 * - Timed yoga warm-up poses (Runner's Lunge, Warrior I/II, Reverse Warrior)
 *   hold 30s with the full Vinyasa entry/exit chain verbatim in `cue`.
 * - Kenpo Karate + core rep drills have no video-fixed duration → `seconds:
 *   null`, `reps` = the primary count, the item detail verbatim in `cue`.
 *   E17's wait UI shows the rep target + a Done — next tap.
 * - Q14 splits flatten a single doc item into consecutive segments sharing an
 *   `exerciseId`, seamless (no lead-in between halves): Standing Quad Stretch
 *   (warm-up + cool-down) → 30s R + 30s L; Squat Run → 30s L + 30s R.
 * - Superman / Banana is ONE 60s timed segment (alternating holds on cue) —
 *   the Q21e "stay one segment" pattern; the doc gives no split durations.
 * - Plyometrics Series: 5 moves × 2 rounds = 10 timed 30s segments; each move
 *   shares an `exerciseId` across its two (non-contiguous) rounds, and Jump
 *   Shot carries the round-difference in its `cue` per the doc.
 * - `leadIn: 5` on the first segment of every exercise instance except the
 *   timeline's first segment; none within splits; Cardio X has no breaks.
 * - Q21c logging (GD default): the 12 rep drills — 10 Kenpo + Squat/Cross/X
 *   Press + Steam Engine — are logged done/skipped; the 2 flows (no reps) and
 *   every timed move are excluded.
 */
export const cardioX: PlayTimeline = {
  workoutKey: 'cardio-x',
  title: 'Cardio X',
  source: 'docs/requirements/cardio-x.md',
  segments: [
    // ── 1. Warm-Up Phase (9 timed segments; Standing Quad split 30R+30L) ────
    {
      id: 'warm-run-in-place',
      exerciseId: 'run-in-place',
      name: 'Run in Place',
      seconds: 60,
      kind: 'exercise',
      section: 'Warm-Up Phase',
    },
    {
      id: 'warm-butt-kicks',
      exerciseId: 'butt-kicks',
      name: 'Butt Kicks (Knees down, heels up)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Knees down, heels up',
      section: 'Warm-Up Phase',
    },
    {
      id: 'warm-jump-rope',
      exerciseId: 'jump-rope',
      name: 'Jump Rope (Low impact / kick out)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Low impact / kick out',
      section: 'Warm-Up Phase',
    },
    {
      id: 'warm-jumping-jacks',
      exerciseId: 'jumping-jacks',
      name: 'Jumping Jacks',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up Phase',
    },
    {
      id: 'warm-wide-leg-forward-fold',
      exerciseId: 'wide-leg-forward-fold',
      name: 'Standing Wide-Leg Forward Fold (Rocking)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Rocking',
      section: 'Warm-Up Phase',
    },
    {
      id: 'warm-pyramid-hamstring-right',
      exerciseId: 'pyramid-hamstring-stretch-right',
      name: 'Pyramid Hamstring Stretch (Right leg forward)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'drive left hip to right ankle',
      section: 'Warm-Up Phase',
    },
    {
      id: 'warm-pyramid-hamstring-left',
      exerciseId: 'pyramid-hamstring-stretch-left',
      name: 'Pyramid Hamstring Stretch (Left leg forward)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'drive right hip to left ankle',
      section: 'Warm-Up Phase',
    },
    // Standing Quad Stretch — one doc item, flattened 30s R + 30s L (Q14 split).
    {
      id: 'warm-standing-quad-right',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — right',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '30s right side, 30s left side',
      section: 'Warm-Up Phase',
    },
    {
      id: 'warm-standing-quad-left',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — left',
      seconds: 30,
      kind: 'exercise',
      // Split continuation — seamless, no get-ready gap.
      section: 'Warm-Up Phase',
    },

    // ── 2. Yoga Warm-Up Series (2 untimed flows + 8 timed 30s poses) ────────
    {
      id: 'sun-salutation-vinyasa-1',
      exerciseId: 'sun-salutation-vinyasa',
      name: 'Sun Salutation Vinyasa 1',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Arms Up -> Swan Dive -> Flat Back -> Plank -> Chaturanga -> Upward Dog -> Plank -> Push-up -> Downward Dog (hold 30s) -> Jump to hands -> Flat Back -> Fold -> Reverse Swan Dive',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'sun-salutation-vinyasa-2',
      exerciseId: 'sun-salutation-vinyasa',
      name: 'Sun Salutation Vinyasa 2',
      seconds: null,
      kind: 'exercise',
      // Continuation of the vinyasa instance (continuous flow): no lead-in.
      cue: 'Same sequence (Downward Dog hold 30s)',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'runners-lunge-right',
      exerciseId: 'runners-lunge-right',
      name: "Runner's Lunge (Right)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa entry to Downward Dog -> Float right heel high -> Swing through to Runner\'s Pose (30s) -> Vinyasa exit',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'runners-lunge-left',
      exerciseId: 'runners-lunge-left',
      name: "Runner's Lunge (Left)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: "Downward Dog -> Float left heel high -> Swing through to Runner's Pose (30s) -> Vinyasa exit",
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'warrior-one-right',
      exerciseId: 'warrior-one-right',
      name: 'Warrior One (Right)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa -> Float right heel -> Swing through -> Warrior One (back heel down, 30s) -> Vinyasa exit',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'warrior-one-left',
      exerciseId: 'warrior-one-left',
      name: 'Warrior One (Left)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Downward Dog -> Float left heel -> Swing through -> Warrior One (30s) -> Vinyasa exit',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'warrior-two-right',
      exerciseId: 'warrior-two-right',
      name: 'Warrior Two (Right)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa -> Float right heel -> Swing through -> Warrior One -> Warrior Two (30s) -> Vinyasa exit',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'warrior-two-left',
      exerciseId: 'warrior-two-left',
      name: 'Warrior Two (Left)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Downward Dog -> Float left heel -> Swing through -> Warrior One -> Warrior Two (30s) -> Vinyasa exit',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'reverse-warrior-right',
      exerciseId: 'reverse-warrior-right',
      name: 'Reverse Warrior (Right)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa -> Float right heel -> Swing through -> Warrior One -> Warrior Two -> Reverse Warrior (30s) -> Vinyasa exit',
      section: 'Yoga Warm-Up Series',
    },
    {
      id: 'reverse-warrior-left',
      exerciseId: 'reverse-warrior-left',
      name: 'Reverse Warrior (Left)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Downward Dog -> Float left heel -> Swing through -> Warrior One -> Warrior Two -> Reverse Warrior (30s) -> Vinyasa exit -> Downward Dog -> Jump/walk feet to hands',
      section: 'Yoga Warm-Up Series',
    },

    // ── 3. Kenpo Karate Series (10 untimed rep drills) ──────────────────────
    {
      id: 'ball-kicks-right',
      exerciseId: 'ball-kicks-right',
      name: 'Ball Kicks / Front Kicks (Right leg / Left stance)',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kenpo Karate Series',
    },
    {
      id: 'ball-kicks-left',
      exerciseId: 'ball-kicks-left',
      name: 'Ball Kicks / Front Kicks (Left leg / Right stance)',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kenpo Karate Series',
    },
    {
      id: 'hook-uppercut-low-sidekick-left',
      exerciseId: 'hook-uppercut-low-sidekick-left',
      name: 'Hook, Uppercut, Low Sidekick (Left stance)',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kenpo Karate Series',
    },
    {
      id: 'hook-uppercut-low-sidekick-right',
      exerciseId: 'hook-uppercut-low-sidekick-right',
      name: 'Hook, Uppercut, Low Sidekick (Right stance)',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kenpo Karate Series',
    },
    {
      id: 'back-knuckles-ball-kick-back-kick-left',
      exerciseId: 'back-knuckles-ball-kick-back-kick-left',
      name: 'Back Knuckles, Ball Kick, Back Kick (Left stance)',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'look back, front, back',
      section: 'Kenpo Karate Series',
    },
    {
      id: 'back-knuckles-ball-kick-back-kick-right',
      exerciseId: 'back-knuckles-ball-kick-back-kick-right',
      name: 'Back Knuckles, Ball Kick, Back Kick (Right stance)',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kenpo Karate Series',
    },
    {
      id: 'jab-cross-hook-uppercut-left',
      exerciseId: 'jab-cross-hook-uppercut-left',
      name: 'Jab, Cross, Hook, Uppercut (Left stance)',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hip-driven rotation',
      section: 'Kenpo Karate Series',
    },
    {
      id: 'jab-cross-hook-uppercut-right',
      exerciseId: 'jab-cross-hook-uppercut-right',
      name: 'Jab, Cross, Hook, Uppercut (Right stance)',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kenpo Karate Series',
    },
    {
      id: 'three-direction-kicks-left',
      exerciseId: 'three-direction-kicks-left',
      name: 'Three Direction Kicks (Front, Side, Back - Left kick/Right support)',
      seconds: null,
      reps: 6,
      kind: 'exercise',
      leadIn: 5,
      cue: '6 full combinations (18 total kicks)',
      section: 'Kenpo Karate Series',
    },
    {
      id: 'three-direction-kicks-right',
      exerciseId: 'three-direction-kicks-right',
      name: 'Three Direction Kicks (Front, Side, Back - Right kick/Left support)',
      seconds: null,
      reps: 6,
      kind: 'exercise',
      leadIn: 5,
      cue: '6 full combinations (18 total kicks)',
      section: 'Kenpo Karate Series',
    },

    // ── 4. Plyometrics Series — Rounds 1 & 2 (10 timed 30s segments) ───────
    {
      id: 'plyo-r1-airborne-heisman',
      exerciseId: 'airborne-heisman',
      name: 'Airborne Heisman — Round 1',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'shuffle side-to-side with balance pause',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r1-swing-kicks',
      exerciseId: 'swing-kicks',
      name: 'Swing Kicks — Round 1',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating legs over chair/stool',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r1-jump-shot',
      exerciseId: 'jump-shot',
      name: 'Jump Shot — Round 1',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Round 1: catch right/shoot left',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r1-monster-truck-tires',
      exerciseId: 'monster-truck-tires',
      name: 'Monster Truck Tires — Round 1',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '4 steps forward, 4 steps back, high knees',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r1-wacky-jacks',
      exerciseId: 'wacky-jacks',
      name: 'Wacky Jacks — Round 1',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'lateral jacks crunched at waist',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r2-airborne-heisman',
      exerciseId: 'airborne-heisman',
      name: 'Airborne Heisman — Round 2',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'shuffle side-to-side with balance pause',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r2-swing-kicks',
      exerciseId: 'swing-kicks',
      name: 'Swing Kicks — Round 2',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating legs over chair/stool',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r2-jump-shot',
      exerciseId: 'jump-shot',
      name: 'Jump Shot — Round 2',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Round 2: catch left/shoot right',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r2-monster-truck-tires',
      exerciseId: 'monster-truck-tires',
      name: 'Monster Truck Tires — Round 2',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '4 steps forward, 4 steps back, high knees',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },
    {
      id: 'plyo-r2-wacky-jacks',
      exerciseId: 'wacky-jacks',
      name: 'Wacky Jacks — Round 2',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'lateral jacks crunched at waist',
      section: 'Plyometrics Series (Rounds 1 & 2)',
    },

    // ── 5. Core Section (2 untimed drills + Dreya Roll + Squat Run split + Superman/Banana)
    {
      id: 'squat-cross-x-press',
      exerciseId: 'squat-cross-x-press',
      name: 'Squat, Cross, X Press',
      seconds: null,
      reps: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'touch floor, reach wide; last 10 reps are jump-squats',
      section: 'Core Section',
    },
    {
      id: 'steam-engine',
      exerciseId: 'steam-engine',
      name: 'Steam Engine',
      seconds: null,
      reps: 50,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hands behind head, high knee twist; starts slow, picks up speed',
      section: 'Core Section',
    },
    {
      id: 'dreya-roll',
      exerciseId: 'dreya-roll',
      name: 'Dreya Roll',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'roll back on spine, roll forward to squat and stand/jump',
      section: 'Core Section',
    },
    // Squat Run — one doc item, flattened 30s L + 30s R (Q14 split).
    {
      id: 'squat-run-left',
      exerciseId: 'squat-run',
      name: 'Squat Run — left foot forward',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'low run stance',
      section: 'Core Section',
    },
    {
      id: 'squat-run-right',
      exerciseId: 'squat-run',
      name: 'Squat Run — right foot forward',
      seconds: 30,
      kind: 'exercise',
      // Split continuation — seamless, no get-ready gap.
      cue: 'low run stance',
      section: 'Core Section',
    },
    // Superman / Banana — one 60s timed segment; alternating holds on cue (Q21e).
    {
      id: 'superman-banana',
      exerciseId: 'superman-banana',
      name: 'Superman / Banana',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating holds on stomach [Superman] and back [Banana] on cue',
      section: 'Core Section',
    },

    // ── 6. Cool Down & Stretch (8 timed segments; Standing Quad split 30R+30L)
    {
      id: 'cd-arm-shakers',
      exerciseId: 'arm-shakers',
      name: 'Arm Shakers',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-jump-rope',
      exerciseId: 'jump-rope',
      name: 'Jump Rope (Low Impact)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-marching-kick',
      exerciseId: 'marching-kick',
      name: 'Marching Kick',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-wide-forward-fold',
      exerciseId: 'wide-forward-fold',
      name: 'Wide Forward Fold (Rocking)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Rocking',
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-downward-dog',
      exerciseId: 'downward-dog-calf-stretch',
      name: 'Downward Dog (Alternating Calf Stretch)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Alternating Calf Stretch',
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-cat-cow',
      exerciseId: 'cat-cow-stretch',
      name: 'Cat/Cow Stretch',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '1 breathing cycle',
      section: 'Cool Down & Stretch',
    },
    // Standing Quad Stretch — flattened 30s R + 30s L (Q14 split).
    {
      id: 'cd-standing-quad-right',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — right',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '30s right side, 30s left side',
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-standing-quad-left',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — left',
      seconds: 30,
      kind: 'exercise',
      // Split continuation — seamless, no get-ready gap.
      section: 'Cool Down & Stretch',
    },
  ],
  loggedExerciseIds: [
    // Kenpo Karate Series (10 rep drills)
    'ball-kicks-right',
    'ball-kicks-left',
    'hook-uppercut-low-sidekick-left',
    'hook-uppercut-low-sidekick-right',
    'back-knuckles-ball-kick-back-kick-left',
    'back-knuckles-ball-kick-back-kick-right',
    'jab-cross-hook-uppercut-left',
    'jab-cross-hook-uppercut-right',
    'three-direction-kicks-left',
    'three-direction-kicks-right',
    // Core Section (2 rep drills)
    'squat-cross-x-press',
    'steam-engine',
  ],
}
