import type { PlayTimeline } from './types'

/**
 * P90X Kenpo X authored play timeline — transcribed verbatim from
 * docs/requirements/kenpo-x.md (the oracle). Order = play order.
 *
 * Locked decisions (see E17 spec §4.1):
 * - Rep-based strikes/kicks have no video-fixed duration → `seconds: null`
 *   (untimed wait; the engine holds until a Done — next / Skip tap). Timed
 *   stretches, cardio-break intervals and the water break count down as in E16.
 * - Every Kenpo item is its own instance — no split continuations — so every
 *   exercise segment is an instance head: `leadIn: 5` on every exercise segment
 *   except the very first of the timeline; the water break gets none.
 * - Section-level preambles (e.g. "Rep-based strikes. Hands up, guard ribs.")
 *   are prefixed onto that section's FIRST segment's `cue`; item-level
 *   parentheticals stay on their own segment's `cue`.
 * - Q21c logging (GD-A): the 45 numbered rep drills + `x-jacks` = 46 unique ids.
 *   Numbered items #36 (Running/Jump Rope Active Recovery) and #37 (Jumping
 *   Jacks) are timed and excluded; #38 X Jacks shares `x-jacks` with the three
 *   cardio-break appearances (ids suffixed -1..-4). Warm-up/cool-down/cardio-
 *   break timed moves are not logged.
 */
export const kenpoX: PlayTimeline = {
  workoutKey: 'kenpo-x',
  title: 'Kenpo X',
  source: 'docs/requirements/kenpo-x.md',
  segments: [
    // ── 1. Warm-Up & Stretch Phase (26 timed segments) ──────────────────────
    {
      id: 'warm-wide-wrist-pull-stretch',
      exerciseId: 'wide-wrist-pull-stretch',
      name: 'Wide Wrist-Pull Stretch (Left/Right)',
      seconds: 60,
      kind: 'exercise',
      // Section preamble prefixed + item parenthetical.
      cue: 'Performed once sequentially. lateral bend, deep fold',
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-prayer-squat-1',
      exerciseId: 'prayer-squat-rocking',
      name: 'Prayer Squat (Rocking)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-side-lunge-flat-foot-r',
      exerciseId: 'side-lunge-flat-foot-stretch',
      name: 'Side Lunge Flat-Foot Stretch — right leg out',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-runners-pose-backbend-r',
      exerciseId: 'runners-pose-backbend',
      name: 'Runner’s Pose with Backbend — right',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knee down, arms up',
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-crescent-pose-r',
      exerciseId: 'crescent-pose',
      name: 'Crescent Pose — right',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-crescent-prayer-twist-r',
      exerciseId: 'crescent-prayer-twist',
      name: 'Crescent Prayer Twist — right',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-prayer-squat-2',
      exerciseId: 'prayer-squat-rocking',
      name: 'Prayer Squat (Rocking)',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-side-lunge-flat-foot-l',
      exerciseId: 'side-lunge-flat-foot-stretch',
      name: 'Side Lunge Flat-Foot Stretch — left leg out',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-runners-pose-backbend-l',
      exerciseId: 'runners-pose-backbend',
      name: 'Runner’s Pose with Backbend — left',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knee down, arms up',
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-crescent-pose-l',
      exerciseId: 'crescent-pose',
      name: 'Crescent Pose — left',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-crescent-prayer-twist-l',
      exerciseId: 'crescent-prayer-twist',
      name: 'Crescent Prayer Twist — left',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-prayer-squat-3',
      exerciseId: 'prayer-squat-rocking',
      name: 'Prayer Squat (Rocking)',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-standing-hamstring-forward-fold',
      exerciseId: 'standing-hamstring-forward-fold',
      name: 'Standing Hamstring Forward Fold (Ragdoll)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-standing-roll-up-1',
      exerciseId: 'standing-roll-up',
      name: 'Standing Roll Up',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-supine-hamstring-r',
      exerciseId: 'supine-hamstring-stretch',
      name: 'Supine Hamstring Stretch — right',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'on back',
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-supine-hip-opener-r',
      exerciseId: 'supine-hip-opener-stretch',
      name: 'Supine Hip Opener Stretch — right leg open to side',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-knee-to-chest-armpit-pull-r',
      exerciseId: 'knee-to-chest-armpit-pull',
      name: 'Knee to Chest Armpit Pull — right',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-supine-hamstring-l',
      exerciseId: 'supine-hamstring-stretch',
      name: 'Supine Hamstring Stretch — left',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'on back',
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-supine-hip-opener-l',
      exerciseId: 'supine-hip-opener-stretch',
      name: 'Supine Hip Opener Stretch — left leg open to side',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-knee-to-chest-armpit-pull-l',
      exerciseId: 'knee-to-chest-armpit-pull',
      name: 'Knee to Chest Armpit Pull — left',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-pigeon-pose',
      exerciseId: 'pigeon-pose',
      name: 'Pigeon Pose (Left & Right)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-quad-stretch-from-pigeon',
      exerciseId: 'quad-stretch-from-pigeon',
      name: 'Quad Stretch from Pigeon (Left & Right)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-frog-stretch',
      exerciseId: 'frog-stretch',
      name: 'Frog Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-cobra-pose',
      exerciseId: 'cobra-pose',
      name: 'Cobra Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-downward-dog',
      exerciseId: 'downward-dog-calf-pedals',
      name: 'Downward Dog (Alternating Calf Pedals)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },
    {
      id: 'warm-standing-roll-up-2',
      exerciseId: 'standing-roll-up',
      name: 'Standing Roll Up',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Stretch Phase',
    },

    // ── 2. Punch Section 1 (12 untimed rep drills) ──────────────────────────
    {
      id: 'p1-twist-pivot-l',
      exerciseId: 'twist-and-pivot-left',
      name: 'Twist and Pivot — left stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      // Section preamble prefixed + item parenthetical.
      cue: 'Rep-based strikes. Hands up, guard ribs. hips & heel rotation',
      section: 'Punch Section 1',
    },
    {
      id: 'p1-twist-pivot-r',
      exerciseId: 'twist-and-pivot-right',
      name: 'Twist and Pivot — right stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-hook-uppercut-l',
      exerciseId: 'hook-uppercut-left',
      name: 'Hook Uppercut — left stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-hook-uppercut-r',
      exerciseId: 'hook-uppercut-right',
      name: 'Hook Uppercut — right stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jabs-l',
      exerciseId: 'jabs-left',
      name: 'Jabs — left stance',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      cue: '20 reps single + 10 reps double-time',
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jabs-r',
      exerciseId: 'jabs-right',
      name: 'Jabs — right stance',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      cue: '20 reps single + 10 reps double-time',
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jab-cross-l',
      exerciseId: 'jab-cross-left',
      name: 'Jab Cross — left stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jab-cross-r',
      exerciseId: 'jab-cross-right',
      name: 'Jab Cross — right stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jab-cross-hook-l',
      exerciseId: 'jab-cross-hook-left',
      name: 'Jab Cross Hook — left stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jab-cross-hook-r',
      exerciseId: 'jab-cross-hook-right',
      name: 'Jab Cross Hook — right stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jab-cross-hook-uppercut-l',
      exerciseId: 'jab-cross-hook-uppercut-left',
      name: 'Jab Cross Hook Uppercut — left stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },
    {
      id: 'p1-jab-cross-hook-uppercut-r',
      exerciseId: 'jab-cross-hook-uppercut-right',
      name: 'Jab Cross Hook Uppercut — right stance',
      seconds: null,
      reps: 25,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 1',
    },

    // ── 3. Cardio Break 1 (2 timed + 1 untimed X Jacks) ─────────────────────
    {
      id: 'cb1-running-in-place',
      exerciseId: 'running-in-place',
      name: 'Running in Place (High Knees)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 1',
    },
    {
      id: 'cb1-jump-rope',
      exerciseId: 'jump-rope',
      name: 'Jump Rope',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 1',
    },
    {
      id: 'cb1-x-jacks-1',
      exerciseId: 'x-jacks',
      name: 'X Jacks (Jump Attacks)',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 1',
    },

    // ── 4. Punch Section 2 (4 untimed rep drills + water break) ─────────────
    {
      id: 'p2-step-drag-punch-l',
      exerciseId: 'step-drag-punch-high-low-left',
      name: 'Step Drag Punch High, Punch Low — left stance',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Stance movement drills. 20 reps regular + 10 reps double-time with yell',
      section: 'Punch Section 2',
    },
    {
      id: 'p2-step-drag-punch-r',
      exerciseId: 'step-drag-punch-high-low-right',
      name: 'Step Drag Punch High, Punch Low — right stance',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      cue: '20 reps regular + 10 reps double-time with yell',
      section: 'Punch Section 2',
    },
    {
      id: 'p2-jab-cross-switch',
      exerciseId: 'jab-cross-switch',
      name: 'Jab Cross Switch (Alternating stances)',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 2',
    },
    {
      id: 'p2-hook-uppercut-switch',
      exerciseId: 'hook-uppercut-switch',
      name: 'Hook Uppercut Switch (Alternating stances)',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      section: 'Punch Section 2',
    },
    {
      id: 'p2-water',
      exerciseId: 'water-break-p2',
      name: 'Water Break',
      seconds: 30,
      kind: 'break',
      section: 'Punch Section 2',
    },

    // ── 5. Kick Section (6 untimed rep drills) ──────────────────────────────
    {
      id: 'ks-knee-kicks-l',
      exerciseId: 'knee-kicks-left',
      name: 'Knee Kicks — left stance',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Thigh leads, lower leg whips. Lean away to kick. 20 reps regular + 10 reps double-time',
      section: 'Kick Section',
    },
    {
      id: 'ks-knee-kicks-r',
      exerciseId: 'knee-kicks-right',
      name: 'Knee Kicks — right stance',
      seconds: null,
      reps: 20,
      kind: 'exercise',
      leadIn: 5,
      cue: '20 reps regular + 10 reps double-time',
      section: 'Kick Section',
    },
    {
      id: 'ks-ball-kicks-l',
      exerciseId: 'ball-kicks-front-kicks-left',
      name: 'Ball Kicks / Front Kicks — left stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps high with yell',
      section: 'Kick Section',
    },
    {
      id: 'ks-ball-kicks-r',
      exerciseId: 'ball-kicks-front-kicks-right',
      name: 'Ball Kicks / Front Kicks — right stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps high with yell',
      section: 'Kick Section',
    },
    {
      id: 'ks-side-kicks-r',
      exerciseId: 'side-kicks-right',
      name: 'Side Kicks — right side, from Horse stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps high/sound',
      section: 'Kick Section',
    },
    {
      id: 'ks-side-kicks-l',
      exerciseId: 'side-kicks-left',
      name: 'Side Kicks — left side, from Horse stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps high/sound',
      section: 'Kick Section',
    },

    // ── 6. Cardio Break 2 (3 timed + 1 untimed X Jacks) ─────────────────────
    {
      id: 'cb2-running-in-place',
      exerciseId: 'running-in-place',
      name: 'Running in Place (High Knees)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 2',
    },
    {
      id: 'cb2-jump-rope',
      exerciseId: 'jump-rope',
      name: 'Jump Rope',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 2',
    },
    {
      id: 'cb2-jumping-jacks',
      exerciseId: 'jumping-jacks',
      name: 'Jumping Jacks',
      seconds: 20,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 2',
    },
    {
      id: 'cb2-x-jacks-2',
      exerciseId: 'x-jacks',
      name: 'X Jacks (Jump Attacks)',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 2',
    },

    // ── 7. Kick & Combo Section (8 untimed rep drills) ──────────────────────
    {
      id: 'kc-back-kicks-r',
      exerciseId: 'back-kicks-right',
      name: 'Back Kicks — kicking right, left stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Advanced defense and counter attacks. 15 reps regular + 10 reps high/yell',
      section: 'Kick & Combo Section',
    },
    {
      id: 'kc-back-kicks-l',
      exerciseId: 'back-kicks-left',
      name: 'Back Kicks — kicking left, right stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps high/yell',
      section: 'Kick & Combo Section',
    },
    {
      id: 'kc-three-direction-kicks-l',
      exerciseId: 'three-direction-kicks-left',
      name: 'Three Direction Kicks — left kick / right support',
      seconds: null,
      reps: 8,
      kind: 'exercise',
      leadIn: 5,
      cue: '8 full combinations (24 total kicks)',
      section: 'Kick & Combo Section',
    },
    {
      id: 'kc-three-direction-kicks-r',
      exerciseId: 'three-direction-kicks-right',
      name: 'Three Direction Kicks — right kick / left support',
      seconds: null,
      reps: 8,
      kind: 'exercise',
      leadIn: 5,
      cue: '8 full combinations (24 total kicks)',
      section: 'Kick & Combo Section',
    },
    {
      id: 'kc-side-lunge-sword-hammer-l',
      exerciseId: 'side-lunge-sword-hammer-left',
      name: 'Side Lunge Sword, Hammer — left side',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kick & Combo Section',
    },
    {
      id: 'kc-side-lunge-sword-hammer-r',
      exerciseId: 'side-lunge-sword-hammer-right',
      name: 'Side Lunge Sword, Hammer — right side',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Kick & Combo Section',
    },
    {
      id: 'kc-step-drag-claw-l',
      exerciseId: 'step-drag-claw-low-punch-left',
      name: 'Step Drag Claw, Low Punch — left stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps double-time with yell',
      section: 'Kick & Combo Section',
    },
    {
      id: 'kc-step-drag-claw-r',
      exerciseId: 'step-drag-claw-low-punch-right',
      name: 'Step Drag Claw, Low Punch — right stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps double-time with yell',
      section: 'Kick & Combo Section',
    },

    // ── 8. Cardio Break 3 (3 timed + 1 untimed X Jacks) ─────────────────────
    {
      id: 'cb3-running-in-place',
      exerciseId: 'running-in-place',
      name: 'Running in Place (High Knees)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 3',
    },
    {
      id: 'cb3-jump-rope',
      exerciseId: 'jump-rope',
      name: 'Jump Rope',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 3',
    },
    {
      id: 'cb3-jumping-jacks',
      exerciseId: 'jumping-jacks',
      name: 'Jumping Jacks',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 3',
    },
    {
      id: 'cb3-x-jacks-3',
      exerciseId: 'x-jacks',
      name: 'X Jacks (Jump Attacks)',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cardio Break 3',
    },

    // ── 9. Blocks & Elbows Section (5 untimed blocks + 2 timed + X Jacks) ───
    {
      id: 'be-high-blocks',
      exerciseId: 'high-blocks',
      name: 'High Blocks (Horse stance)',
      seconds: null,
      reps: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Defensive covers and close-range strikes. 30 reps per side (60 total blocks)',
      section: 'Blocks & Elbows Section',
    },
    {
      id: 'be-inward-blocks',
      exerciseId: 'inward-blocks',
      name: 'Inward Blocks (Horse stance)',
      seconds: null,
      reps: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '30 reps per side (60 total blocks)',
      section: 'Blocks & Elbows Section',
    },
    {
      id: 'be-outward-blocks',
      exerciseId: 'outward-blocks',
      name: 'Outward Blocks (Horse stance)',
      seconds: null,
      reps: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '30 reps per side (60 total blocks)',
      section: 'Blocks & Elbows Section',
    },
    {
      id: 'be-downward-blocks',
      exerciseId: 'downward-blocks',
      name: 'Downward Blocks (Horse stance)',
      seconds: null,
      reps: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '30 reps per side (60 total blocks)',
      section: 'Blocks & Elbows Section',
    },
    {
      id: 'be-star-blocks',
      exerciseId: 'star-blocks',
      name: 'Star Blocks (Fighting stance — High/In/Out/Down Combo)',
      seconds: null,
      reps: 4,
      kind: 'exercise',
      leadIn: 5,
      cue: '2 passes forward, 2 passes back',
      section: 'Blocks & Elbows Section',
    },
    {
      id: 'be-running-jump-rope-recovery',
      exerciseId: 'running-jump-rope-recovery',
      name: 'Running / Jump Rope Active Recovery',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      section: 'Blocks & Elbows Section',
    },
    {
      id: 'be-jumping-jacks',
      exerciseId: 'jumping-jacks',
      name: 'Jumping Jacks',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Blocks & Elbows Section',
    },
    {
      id: 'be-x-jacks-4',
      exerciseId: 'x-jacks',
      name: 'X Jacks (Jump Attacks)',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Blocks & Elbows Section',
    },

    // ── 10. Finishing Combos & Burnout (10 untimed rep drills) ──────────────
    {
      id: 'fc-front-shuffle-l',
      exerciseId: 'front-shuffle-high-block-low-punch-left',
      name: 'Front Shuffle High Block, Low Punch — left stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Ultimate combinations and high-speed punchout. 15 reps regular + 10 reps spirit yell',
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-front-shuffle-r',
      exerciseId: 'front-shuffle-high-block-low-punch-right',
      name: 'Front Shuffle High Block, Low Punch — right stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '15 reps regular + 10 reps spirit yell',
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-knee-back-kick-l',
      exerciseId: 'knee-back-kick-combo-left',
      name: 'Knee, Back Kick Combo — left stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-knee-back-kick-r',
      exerciseId: 'knee-back-kick-combo-right',
      name: 'Knee, Back Kick Combo — right stance',
      seconds: null,
      reps: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-back-knuckles-ball-kick-back-kick-l',
      exerciseId: 'back-knuckles-ball-kick-back-kick-left',
      name: 'Back Knuckles, Ball Kick, Back Kick — left stance',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-back-knuckles-ball-kick-back-kick-r',
      exerciseId: 'back-knuckles-ball-kick-back-kick-right',
      name: 'Back Knuckles, Ball Kick, Back Kick — right stance',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-hook-uppercut-low-sidekick-l',
      exerciseId: 'hook-uppercut-low-sidekick-left',
      name: 'Hook, Uppercut, Low Sidekick — left stance',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-hook-uppercut-low-sidekick-r',
      exerciseId: 'hook-uppercut-low-sidekick-right',
      name: 'Hook, Uppercut, Low Sidekick — right stance',
      seconds: null,
      reps: 10,
      kind: 'exercise',
      leadIn: 5,
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-elbow-series',
      exerciseId: 'elbow-series',
      name: 'Elbow Series (Up, Down, Across — Horse stance)',
      seconds: null,
      reps: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '30 sets (90 total elbow strikes)',
      section: 'Finishing Combos & Burnout',
    },
    {
      id: 'fc-vertical-punching-burnout',
      exerciseId: 'vertical-punching-burnout',
      name: 'Vertical Punching Burnout (Horse stance)',
      seconds: null,
      reps: 100,
      kind: 'exercise',
      leadIn: 5,
      cue: '100+ reps — starts slow, increases to maximum speed',
      section: 'Finishing Combos & Burnout',
    },

    // ── 11. Cool Down & Stretch Phase (7 timed segments) ────────────────────
    {
      id: 'cd-arm-shake-out',
      exerciseId: 'arm-shake-out',
      name: 'Arm Shake-out',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Performed once sequentially',
      section: 'Cool Down & Stretch Phase',
    },
    {
      id: 'cd-jump-rope',
      exerciseId: 'jump-rope',
      name: 'Jump Rope (Low Impact)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch Phase',
    },
    {
      id: 'cd-marching-kick',
      exerciseId: 'marching-kick',
      name: 'Marching Kick',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch Phase',
    },
    {
      id: 'cd-wide-forward-fold',
      exerciseId: 'wide-forward-fold',
      name: 'Wide Forward Fold (Rocking side-to-side)',
      seconds: 90,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch Phase',
    },
    {
      id: 'cd-downward-dog',
      exerciseId: 'downward-dog-calf-pedals',
      name: 'Downward Dog (Alternating calf pedals)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch Phase',
    },
    {
      id: 'cd-standing-roll-up',
      exerciseId: 'standing-roll-up',
      name: 'Standing Roll Up',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'slow 10-count',
      section: 'Cool Down & Stretch Phase',
    },
    {
      id: 'cd-standing-quad-stretch',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: '30s right, 30s left',
      section: 'Cool Down & Stretch Phase',
    },
  ],
  loggedExerciseIds: [
    // Punch Section 1 (#1–#12)
    'twist-and-pivot-left',
    'twist-and-pivot-right',
    'hook-uppercut-left',
    'hook-uppercut-right',
    'jabs-left',
    'jabs-right',
    'jab-cross-left',
    'jab-cross-right',
    'jab-cross-hook-left',
    'jab-cross-hook-right',
    'jab-cross-hook-uppercut-left',
    'jab-cross-hook-uppercut-right',
    // Punch Section 2 (#13–#16)
    'step-drag-punch-high-low-left',
    'step-drag-punch-high-low-right',
    'jab-cross-switch',
    'hook-uppercut-switch',
    // Kick Section (#17–#22)
    'knee-kicks-left',
    'knee-kicks-right',
    'ball-kicks-front-kicks-left',
    'ball-kicks-front-kicks-right',
    'side-kicks-right',
    'side-kicks-left',
    // Kick & Combo Section (#23–#30)
    'back-kicks-right',
    'back-kicks-left',
    'three-direction-kicks-left',
    'three-direction-kicks-right',
    'side-lunge-sword-hammer-left',
    'side-lunge-sword-hammer-right',
    'step-drag-claw-low-punch-left',
    'step-drag-claw-low-punch-right',
    // Blocks & Elbows Section (#31–#35, #38)
    'high-blocks',
    'inward-blocks',
    'outward-blocks',
    'downward-blocks',
    'star-blocks',
    'x-jacks',
    // Finishing Combos & Burnout (#39–#48)
    'front-shuffle-high-block-low-punch-left',
    'front-shuffle-high-block-low-punch-right',
    'knee-back-kick-combo-left',
    'knee-back-kick-combo-right',
    'back-knuckles-ball-kick-back-kick-left',
    'back-knuckles-ball-kick-back-kick-right',
    'hook-uppercut-low-sidekick-left',
    'hook-uppercut-low-sidekick-right',
    'elbow-series',
    'vertical-punching-burnout',
  ],
}
