import type { PlayTimeline } from './types'

/**
 * P90X3 Yoga authored play timeline — transcribed verbatim from
 * docs/requirements/yoga.md (Part 2, the oracle). Order = play order.
 *
 * Locked decisions (see E19 spec §1 + §3):
 * - Ranges are rounded to the nearest 15s midpoint, keeping the verbatim
 *   range in the cue (GD-D): Shavasana 1-2 min -> 90s.
 * - Stated sub-holds are split into sequential timed segments sharing
 *   exerciseId, seamless (no lead-in between halves).
 * - Sun Salutation A rounds are continuous untimed flows (seconds: null).
 * - Exits without stated durations are flows (seconds: null).
 * - All other holds are timed as stated.
 */
export const yogaX3: PlayTimeline = {
  workoutKey: 'yoga-x',
  variant: 'x3',
  title: 'Yoga (P90X3, 30 min)',
  source: 'docs/requirements/yoga.md',
  segments: [
    // ── 1. Warm-Up Phase (4 timed segments) ────────────────────────────────
    {
      id: 'childs-pose-x3',
      exerciseId: 'childs-pose-x3',
      name: "Child's Pose",
      seconds: 45,
      kind: 'exercise',
      cue: 'knees wide, hips back, forehead to mat',
      section: 'Warm-Up Phase',
    },
    {
      id: 'downward-dog-x3',
      exerciseId: 'downward-dog-x3',
      name: 'Downward Dog',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hips high, heels down',
      section: 'Warm-Up Phase',
    },
    {
      id: 'forward-fold-x3',
      exerciseId: 'forward-fold-x3',
      name: 'Forward Fold (Forward Hang)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up Phase',
    },
    {
      id: 'standing-roll-up-x3',
      exerciseId: 'standing-roll-up-x3',
      name: 'Standing Roll Up',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up Phase',
    },

    // ── 2. Sun Salutation A (3 untimed flows) ──────────────────────────────
    {
      id: 'sun-salutation-a-1-x3',
      exerciseId: 'sun-salutation-a-x3',
      name: 'Round 1',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Arms Up -> Swan Dive -> Flat Back -> Plank -> Chaturanga -> Upward Dog -> Downward Dog (hold 15s) -> Step/Jump to Hands -> Halfway Up -> Forward Fold -> Reverse Swan Dive',
      section: 'Sun Salutation A',
    },
    {
      id: 'sun-salutation-a-2-x3',
      exerciseId: 'sun-salutation-a-x3',
      name: 'Round 2',
      seconds: null,
      kind: 'exercise',
      cue: 'Arms Up -> Swan Dive -> Flat Back -> Float/Step to Plank -> Chaturanga -> Upward Dog -> Downward Dog (hold 15s) -> Float/Jump to Hands -> Halfway Up -> Forward Fold -> Reverse Swan Dive',
      section: 'Sun Salutation A',
    },
    {
      id: 'sun-salutation-a-3-x3',
      exerciseId: 'sun-salutation-a-x3',
      name: 'Round 3',
      seconds: null,
      kind: 'exercise',
      cue: 'Arms Up -> Swan Dive -> Flat Back -> Float/Step to Plank -> Chaturanga -> Upward Dog -> Push-up -> Downward Dog (with 6 alternating calf pedals) -> Float/Jump to Hands -> Halfway Up -> Forward Fold -> Reverse Swan Dive',
      section: 'Sun Salutation A',
    },

    // ── 3. Crescent Series (6 timed segments) ──────────────────────────────
    {
      id: 'crescent-lunge-right-x3',
      exerciseId: 'crescent-lunge-series-right-x3',
      name: 'Crescent Lunge (Right side)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa entry -> Right leg swing through -> Crescent Lunge',
      section: 'Crescent Series',
    },
    {
      id: 'airplane-pose-right-x3',
      exerciseId: 'crescent-lunge-series-right-x3',
      name: 'Airplane Pose (Right side)',
      seconds: 30,
      kind: 'exercise',
      cue: 'arms wide, torso leaned forward over thigh',
      section: 'Crescent Series',
    },
    {
      id: 'airplane-with-clasp-right-x3',
      exerciseId: 'crescent-lunge-series-right-x3',
      name: 'Airplane with Clasp (Right side)',
      seconds: 30,
      kind: 'exercise',
      cue: 'clasp hands behind back, drop chest inside knee; exit to Crescent Lunge -> Vinyasa exit',
      section: 'Crescent Series',
    },
    {
      id: 'crescent-lunge-left-x3',
      exerciseId: 'crescent-lunge-series-left-x3',
      name: 'Crescent Lunge (Left side)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Left leg swing through -> Crescent Lunge',
      section: 'Crescent Series',
    },
    {
      id: 'airplane-pose-left-x3',
      exerciseId: 'crescent-lunge-series-left-x3',
      name: 'Airplane Pose (Left side)',
      seconds: 30,
      kind: 'exercise',
      cue: 'arms wide, torso leaned forward over thigh',
      section: 'Crescent Series',
    },
    {
      id: 'airplane-with-clasp-left-x3',
      exerciseId: 'crescent-lunge-series-left-x3',
      name: 'Airplane with Clasp (Left side)',
      seconds: 30,
      kind: 'exercise',
      cue: 'clasp hands behind back, drop chest inside knee; exit to Crescent Lunge -> Vinyasa exit',
      section: 'Crescent Series',
    },

    // ── 4. Sun Salutation B & Bound Side Angle Series (9 segments) ─────────
    {
      id: 'warrior-one-right-x3',
      exerciseId: 'warrior-series-right-x3',
      name: 'Warrior One (Right side)',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa Cycle to Warrior 1 (heel down)',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'warrior-two-right-x3',
      exerciseId: 'warrior-series-right-x3',
      name: 'Warrior Two (Right side)',
      seconds: 15,
      kind: 'exercise',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'reverse-warrior-right-x3',
      exerciseId: 'warrior-series-right-x3',
      name: 'Reverse Warrior (Right side)',
      seconds: 15,
      kind: 'exercise',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'bound-side-angle-right-x3',
      exerciseId: 'warrior-series-right-x3',
      name: 'Bound Side Angle / Forearm on Thigh (Right side)',
      seconds: 30,
      kind: 'exercise',
      cue: 'exit: Warrior Two -> Warrior One -> Vinyasa exit',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'warrior-one-left-x3',
      exerciseId: 'warrior-series-left-x3',
      name: 'Warrior One (Left side)',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa Cycle to Warrior 1 (heel down)',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'warrior-two-left-x3',
      exerciseId: 'warrior-series-left-x3',
      name: 'Warrior Two (Left side)',
      seconds: 15,
      kind: 'exercise',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'reverse-warrior-left-x3',
      exerciseId: 'warrior-series-left-x3',
      name: 'Reverse Warrior (Left side)',
      seconds: 15,
      kind: 'exercise',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'bound-side-angle-left-x3',
      exerciseId: 'warrior-series-left-x3',
      name: 'Bound Side Angle / Forearm on Thigh (Left side)',
      seconds: 30,
      kind: 'exercise',
      cue: 'exit: Warrior Two -> Warrior One -> Vinyasa exit',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'chair-pose-1-x3',
      exerciseId: 'chair-pose-x3',
      name: 'Chair Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Jump/step to hands -> Chair Pose (knees/feet together, weight in heels)',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },
    {
      id: 'chair-exit-sequence-x3',
      exerciseId: 'chair-exit-sequence-x3',
      name: 'Exit Sequence',
      seconds: null,
      kind: 'exercise',
      cue: 'Stand up -> Backbend -> Swan Dive -> Vinyasa exit',
      section: 'Sun Salutation B & Bound Side Angle Series',
    },

    // ── 5. Balance & Split Series (10 segments) ───────────────────────────
    {
      id: 'warrior-three-right-x3',
      exerciseId: 'warrior-balance-right-x3',
      name: 'Warrior Three (Right side support)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Crescent Lunge -> Warrior Three (raise left leg)',
      section: 'Balance & Split Series',
    },
    {
      id: 'half-moon-right-x3',
      exerciseId: 'warrior-balance-right-x3',
      name: 'Half Moon Pose (Right side support)',
      seconds: 30,
      kind: 'exercise',
      cue: 'right hand down, left arm/hip open',
      section: 'Balance & Split Series',
    },
    {
      id: 'revolved-half-moon-right-x3',
      exerciseId: 'warrior-balance-right-x3',
      name: 'Revolved Half Moon (Right side support)',
      seconds: 30,
      kind: 'exercise',
      cue: 'left hand down, right arm/hip open',
      section: 'Balance & Split Series',
    },
    {
      id: 'standing-square-splits-right-x3',
      exerciseId: 'warrior-balance-right-x3',
      name: 'Standing Square Splits (Right side support)',
      seconds: 30,
      kind: 'exercise',
      cue: 'both hands down, nose to knee, left leg up; exit: Crescent Lunge -> Vinyasa exit',
      section: 'Balance & Split Series',
    },
    {
      id: 'warrior-three-left-x3',
      exerciseId: 'warrior-balance-left-x3',
      name: 'Warrior Three (Left side support)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Crescent Lunge -> Warrior Three (raise right leg)',
      section: 'Balance & Split Series',
    },
    {
      id: 'half-moon-left-x3',
      exerciseId: 'warrior-balance-left-x3',
      name: 'Half Moon Pose (Left side support)',
      seconds: 30,
      kind: 'exercise',
      cue: 'left hand down, right arm/hip open',
      section: 'Balance & Split Series',
    },
    {
      id: 'revolved-half-moon-left-x3',
      exerciseId: 'warrior-balance-left-x3',
      name: 'Revolved Half Moon (Left side support)',
      seconds: 30,
      kind: 'exercise',
      cue: 'right hand down, left arm/hip open',
      section: 'Balance & Split Series',
    },
    {
      id: 'standing-square-splits-left-x3',
      exerciseId: 'warrior-balance-left-x3',
      name: 'Standing Square Splits (Left side support)',
      seconds: 30,
      kind: 'exercise',
      cue: 'both hands down, nose to knee, right leg up; exit: Crescent Lunge -> Vinyasa exit',
      section: 'Balance & Split Series',
    },
    {
      id: 'chair-pose-2-x3',
      exerciseId: 'chair-pose-x3',
      name: 'Chair Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Jump to hands -> Chair Pose',
      section: 'Balance & Split Series',
    },
    {
      id: 'balance-exit-x3',
      exerciseId: 'balance-exit-x3',
      name: 'Exit',
      seconds: null,
      kind: 'exercise',
      cue: 'Stand up -> Prayer',
      section: 'Balance & Split Series',
    },

    // ── 6. Wide Stance & Triangle Series (5 timed segments) ────────────────
    {
      id: 'wide-leg-forward-fold-x3',
      exerciseId: 'wide-leg-forward-fold-x3',
      name: 'Wide-Leg Forward Fold',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'straddle mat, toes/heels aligned, fold forward, grab toes -> Flat Back inhale -> Stand up',
      section: 'Wide Stance & Triangle Series',
    },
    {
      id: 'triangle-pose-right-x3',
      exerciseId: 'triangle-pose-right-x3',
      name: 'Triangle Pose (Right side)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'turn right toe out, reach right arm down, left arm up',
      section: 'Wide Stance & Triangle Series',
    },
    {
      id: 'triangle-pose-left-x3',
      exerciseId: 'triangle-pose-left-x3',
      name: 'Triangle Pose (Left side)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'turn left toe out, reach left arm down, right arm up',
      section: 'Wide Stance & Triangle Series',
    },
    {
      id: 'twisting-triangle-right-x3',
      exerciseId: 'twisting-triangle-right-x3',
      name: 'Twisting Triangle (Right side)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left hand inside/outside right foot or on block, right arm up',
      section: 'Wide Stance & Triangle Series',
    },
    {
      id: 'twisting-triangle-left-x3',
      exerciseId: 'twisting-triangle-left-x3',
      name: 'Twisting Triangle (Left side)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right hand inside/outside left foot, left arm up',
      section: 'Wide Stance & Triangle Series',
    },

    // ── 7. Standing Balances & Crow Pose (7 timed segments) ────────────────
    {
      id: 'tree-pose-right-x3',
      exerciseId: 'tree-pose-right-x3',
      name: 'Tree Pose (Right side support)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left foot on inner right thigh, hands in prayer or overhead',
      section: 'Standing Balances & Crow Pose',
    },
    {
      id: 'tree-pose-left-x3',
      exerciseId: 'tree-pose-left-x3',
      name: 'Tree Pose (Left side support)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right foot on inner left thigh',
      section: 'Standing Balances & Crow Pose',
    },
    {
      id: 'extended-leg-toe-bind-right-x3',
      exerciseId: 'extended-leg-toe-bind-right-x3',
      name: 'Extended Leg with Toe Bind (Right side support)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'grab left big toe, extend left leg forward/out',
      section: 'Standing Balances & Crow Pose',
    },
    {
      id: 'extended-leg-toe-bind-left-x3',
      exerciseId: 'extended-leg-toe-bind-left-x3',
      name: 'Extended Leg with Toe Bind (Left side support)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'grab right big toe, extend right leg forward/out',
      section: 'Standing Balances & Crow Pose',
    },
    {
      id: 'teds-chair-right-x3',
      exerciseId: 'teds-chair-right-x3',
      name: "Ted's Chair / Figure 4 Balance (Right side support)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'cross left ankle above right knee, drop hips into single-leg chair; optional arm balance',
      section: 'Standing Balances & Crow Pose',
    },
    {
      id: 'teds-chair-left-x3',
      exerciseId: 'teds-chair-left-x3',
      name: "Ted's Chair / Figure 4 Balance (Left side support)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'cross right ankle above left knee, drop hips; optional arm balance',
      section: 'Standing Balances & Crow Pose',
    },
    {
      id: 'crow-pose-x3',
      exerciseId: 'crow-pose-x3',
      name: 'Crow Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: "knees on triceps, float feet; 3 breaths -> Chaturanga shootback -> Vinyasa -> Child's Pose (brief)",
      section: 'Standing Balances & Crow Pose',
    },

    // ── 8. Spine & Floor Series (20 timed segments) ────────────────────────
    {
      id: 'cat-dog-tilt-x3',
      exerciseId: 'cat-dog-tilt-x3',
      name: 'Cat/Dog Tilt (Cat/Cow)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: '3 breathing cycles on hands and knees',
      section: 'Spine & Floor Series',
    },
    {
      id: 'bird-dog-right-x3',
      exerciseId: 'bird-dog-right-x3',
      name: 'Bird Dog (Right side / Dog Dancer)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right arm forward, left leg back; grab ankle to lift chest',
      section: 'Spine & Floor Series',
    },
    {
      id: 'bird-dog-left-x3',
      exerciseId: 'bird-dog-left-x3',
      name: 'Bird Dog (Left side / Dog Dancer)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left arm forward, right leg back; grab ankle',
      section: 'Spine & Floor Series',
    },
    {
      id: 'camel-pose-x3',
      exerciseId: 'camel-pose-x3',
      name: 'Camel Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knees down, hips forward, hands to heels, head back; 5 breaths',
      section: 'Spine & Floor Series',
    },
    // Hamstring series: Right leg straight (4 segments)
    {
      id: 'seated-single-leg-fold-right-x3',
      exerciseId: 'hamstring-series-right-x3',
      name: 'Seated Single-Leg Fold (Right leg straight)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left foot to inner thigh, fold forward',
      section: 'Spine & Floor Series',
    },
    {
      id: 'seated-figure-four-fold-right-x3',
      exerciseId: 'hamstring-series-right-x3',
      name: 'Seated Figure Four Fold (Right leg straight)',
      seconds: 30,
      kind: 'exercise',
      cue: 'left ankle on right thigh, fold forward',
      section: 'Spine & Floor Series',
    },
    {
      id: 'seated-figure-four-butt-pull-right-x3',
      exerciseId: 'hamstring-series-right-x3',
      name: 'Seated Figure Four Ankle-to-Butt Pull (Right leg straight)',
      seconds: 30,
      kind: 'exercise',
      cue: 'pigeon/glute pull',
      section: 'Spine & Floor Series',
    },
    {
      id: 'seated-twist-right-x3',
      exerciseId: 'hamstring-series-right-x3',
      name: 'Seated Twist (Right leg straight)',
      seconds: 30,
      kind: 'exercise',
      cue: 'drop left foot to floor outside right leg, twist right',
      section: 'Spine & Floor Series',
    },
    // Hamstring series: Left leg straight (4 segments)
    {
      id: 'seated-single-leg-fold-left-x3',
      exerciseId: 'hamstring-series-left-x3',
      name: 'Seated Single-Leg Fold (Left leg straight)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Spine & Floor Series',
    },
    {
      id: 'seated-figure-four-fold-left-x3',
      exerciseId: 'hamstring-series-left-x3',
      name: 'Seated Figure Four Fold (Left leg straight)',
      seconds: 30,
      kind: 'exercise',
      section: 'Spine & Floor Series',
    },
    {
      id: 'seated-figure-four-butt-pull-left-x3',
      exerciseId: 'hamstring-series-left-x3',
      name: 'Seated Figure Four Ankle-to-Butt Pull (Left leg straight)',
      seconds: 30,
      kind: 'exercise',
      section: 'Spine & Floor Series',
    },
    {
      id: 'seated-twist-left-x3',
      exerciseId: 'hamstring-series-left-x3',
      name: 'Seated Twist (Left leg straight)',
      seconds: 30,
      kind: 'exercise',
      section: 'Spine & Floor Series',
    },
    {
      id: 'plow-pose-x3',
      exerciseId: 'plow-pose-x3',
      name: 'Plow Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'lie on back, drop feet overhead',
      section: 'Spine & Floor Series',
    },
    {
      id: 'shoulder-stand-x3',
      exerciseId: 'shoulder-stand-x3',
      name: 'Shoulder Stand',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'support lower back, legs vertical',
      section: 'Spine & Floor Series',
    },
    {
      id: 'vertebrae-roll-down-x3',
      exerciseId: 'vertebrae-roll-down-x3',
      name: 'Vertebrae Roll Down',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'slow roll out to knees-to-ears',
      section: 'Spine & Floor Series',
    },
    {
      id: 'fish-pose-x3',
      exerciseId: 'fish-pose-x3',
      name: 'Fish Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'up on forearms, chest up, head back',
      section: 'Spine & Floor Series',
    },
    {
      id: 'shavasana-x3',
      exerciseId: 'shavasana-x3',
      name: 'Shavasana (Final Relaxation)',
      seconds: 90, // GD-D midpoint of 1-2 min
      kind: 'exercise',
      leadIn: 5,
      cue: 'lying flat (~1-2 min)',
      section: 'Spine & Floor Series',
    },
  ],
  loggedExerciseIds: [],
}
