import type { PlayTimeline } from './types'

/**
 * P90X Plyometrics authored interval timeline — transcribed verbatim from
 * docs/requirements/plyometrics.md (the oracle). Order = play order.
 *
 * Locked decisions applied (see requirements doc §Locked decisions):
 * - Q13b: ~5s get-ready gap (`leadIn: 5`) before the first segment of every
 *   exercise instance except the very first segment of the timeline.
 * - Q14: every internal split flattened into its own segment (beep at switch).
 * - Q21a: water break after every block's round 2, including block 5.
 * - Q21d: Circle Run round 2 reversed (CCW then CW).
 * - Q21e: Lunges stay one 90s segment.
 * - Q21c: loggedExerciseIds = the 23 block + bonus jump moves (warm-up/cool-down excluded).
 */
export const plyometrics: PlayTimeline = {
  workoutKey: 'plyometrics',
  title: 'Plyometrics',
  source: 'docs/requirements/plyometrics.md',
  segments: [
    // ── Warm-Up (11 segments) ──────────────────────────────────────────────
    {
      id: 'warm-march-in-place',
      exerciseId: 'march-in-place',
      name: 'March in Place',
      seconds: 30,
      kind: 'exercise',
      section: 'Warm-Up',
    },
    {
      id: 'warm-run-in-place',
      exerciseId: 'run-in-place',
      name: 'Run in Place',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up',
    },
    {
      id: 'warm-butt-kicks',
      exerciseId: 'knees-down-heels-up',
      name: 'Knees Down, Heels Up (Butt Kicks)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up',
    },
    // Tires & Mary Katherine (Mini) — flattened 15s + 15s (Q14)
    {
      id: 'warm-tires-mk-1',
      exerciseId: 'tires-mary-katherine-mini',
      name: 'Tires & Mary Katherine (Mini) — part 1',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up',
    },
    {
      id: 'warm-tires-mk-2',
      exerciseId: 'tires-mary-katherine-mini',
      name: 'Tires & Mary Katherine (Mini) — part 2',
      seconds: 15,
      kind: 'exercise',
      section: 'Warm-Up',
    },
    // Lunges — one 90s segment (Q21e)
    {
      id: 'warm-lunges',
      exerciseId: 'lunges',
      name: 'Lunges (Alternating)',
      seconds: 90,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating',
      section: 'Warm-Up',
    },
    {
      id: 'warm-prayer-squats',
      exerciseId: 'deep-prayer-squats',
      name: 'Deep Prayer Squats',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: '30 repetitions',
      section: 'Warm-Up',
    },
    // Standing Quad Stretch — flattened R 30s + L 30s (Q14)
    {
      id: 'warm-quad-stretch-r',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — right',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up',
    },
    {
      id: 'warm-quad-stretch-l',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — left',
      seconds: 30,
      kind: 'exercise',
      section: 'Warm-Up',
    },
    // Hamstring Stretch — flattened R 30s + L 30s (Q14)
    {
      id: 'warm-hamstring-r',
      exerciseId: 'hamstring-stretch',
      name: 'Hamstring Stretch (Standing) — right leg forward',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up',
    },
    {
      id: 'warm-hamstring-l',
      exerciseId: 'hamstring-stretch',
      name: 'Hamstring Stretch (Standing) — left leg forward',
      seconds: 30,
      kind: 'exercise',
      section: 'Warm-Up',
    },

    // ── Block 1 — Round 1 (4) + Round 2 (4) + Water (1) = 9 segments ───────
    {
      id: 'b1-r1-jump-squats',
      exerciseId: 'jump-squats',
      name: 'Jump Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 1 — Round 1',
    },
    {
      id: 'b1-r1-run-stance-squats',
      exerciseId: 'run-stance-squats',
      name: 'Run Stance Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '3 squats, jump on 4th',
      section: 'Block 1 — Round 1',
    },
    {
      id: 'b1-r1-airborne-heisman',
      exerciseId: 'airborne-heisman',
      name: 'Airborne Heisman',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 1 — Round 1',
    },
    {
      id: 'b1-r1-swing-kicks',
      exerciseId: 'swing-kicks',
      name: 'Swing Kicks',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating legs over chair/stool',
      section: 'Block 1 — Round 1',
    },
    {
      id: 'b1-r2-jump-squats',
      exerciseId: 'jump-squats',
      name: 'Jump Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 1 — Round 2',
    },
    {
      id: 'b1-r2-run-stance-squats',
      exerciseId: 'run-stance-squats',
      name: 'Run Stance Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '3 squats, jump on 4th',
      section: 'Block 1 — Round 2',
    },
    {
      id: 'b1-r2-airborne-heisman',
      exerciseId: 'airborne-heisman',
      name: 'Airborne Heisman',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 1 — Round 2',
    },
    {
      id: 'b1-r2-swing-kicks',
      exerciseId: 'swing-kicks',
      name: 'Swing Kicks',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating legs over chair/stool',
      section: 'Block 1 — Round 2',
    },
    {
      id: 'b1-water',
      exerciseId: 'water-break-b1',
      name: 'Water Break',
      seconds: 30,
      kind: 'break',
      section: 'Block 1 — Round 2',
    },

    // ── Block 2 — R1 (5) + R2 (5) + Water (1) = 11 segments ────────────────
    {
      id: 'b2-r1-squat-reach-jump',
      exerciseId: 'squat-reach-jump',
      name: 'Squat Reach Jump',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'touch floor, jump up',
      section: 'Block 2 — Round 1',
    },
    {
      id: 'b2-r1-run-stance-squat-switch-pickup',
      exerciseId: 'run-stance-squat-switch-pickup',
      name: 'Run Stance Squat Switch Pickup',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'land-squat-pivot 180',
      section: 'Block 2 — Round 1',
    },
    {
      id: 'b2-r1-double-airborne-heisman',
      exerciseId: 'double-airborne-heisman',
      name: 'Double Airborne Heisman',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'double side-shuffles with Heisman hold',
      section: 'Block 2 — Round 1',
    },
    // Circle Run R1 — CW then CCW (flattened, Q14)
    {
      id: 'b2-r1-circle-run-cw',
      exerciseId: 'circle-run',
      name: 'Circle Run — clockwise',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 2 — Round 1',
    },
    {
      id: 'b2-r1-circle-run-ccw',
      exerciseId: 'circle-run',
      name: 'Circle Run — counterclockwise',
      seconds: 30,
      kind: 'exercise',
      section: 'Block 2 — Round 1',
    },
    {
      id: 'b2-r2-squat-reach-jump',
      exerciseId: 'squat-reach-jump',
      name: 'Squat Reach Jump',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'touch floor, jump up',
      section: 'Block 2 — Round 2',
    },
    {
      id: 'b2-r2-run-stance-squat-switch-pickup',
      exerciseId: 'run-stance-squat-switch-pickup',
      name: 'Run Stance Squat Switch Pickup',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'land-squat-pivot 180',
      section: 'Block 2 — Round 2',
    },
    {
      id: 'b2-r2-double-airborne-heisman',
      exerciseId: 'double-airborne-heisman',
      name: 'Double Airborne Heisman',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'double side-shuffles with Heisman hold',
      section: 'Block 2 — Round 2',
    },
    // Circle Run R2 — reversed: CCW then CW (Q21d)
    {
      id: 'b2-r2-circle-run-ccw',
      exerciseId: 'circle-run',
      name: 'Circle Run — counterclockwise',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 2 — Round 2',
    },
    {
      id: 'b2-r2-circle-run-cw',
      exerciseId: 'circle-run',
      name: 'Circle Run — clockwise',
      seconds: 30,
      kind: 'exercise',
      section: 'Block 2 — Round 2',
    },
    {
      id: 'b2-water',
      exerciseId: 'water-break-b2',
      name: 'Water Break',
      seconds: 30,
      kind: 'break',
      section: 'Block 2 — Round 2',
    },

    // ── Block 3 — R1 (5) + R2 (5) + Water (1) = 11 segments ────────────────
    {
      id: 'b3-r1-jump-knee-tuck',
      exerciseId: 'jump-knee-tuck',
      name: 'Jump Knee Tuck',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knees to chest',
      section: 'Block 3 — Round 1',
    },
    {
      id: 'b3-r1-mary-katherine',
      exerciseId: 'mary-katherine',
      name: 'Mary Katherine (Jump Lunges)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 3 — Round 1',
    },
    {
      id: 'b3-r1-leapfrog-squats',
      exerciseId: 'leapfrog-squats',
      name: 'Leapfrog Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '2 forward, 2 back',
      section: 'Block 3 — Round 1',
    },
    // Twist Combo — flattened 3-way 30s + 180° 30s (Q14)
    {
      id: 'b3-r1-twist-combo-3way',
      exerciseId: 'twist-combo',
      name: 'Twist Combo — 3-way twist',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left-center-right',
      section: 'Block 3 — Round 1',
    },
    {
      id: 'b3-r1-twist-combo-180',
      exerciseId: 'twist-combo',
      name: 'Twist Combo — 180-degree twist',
      seconds: 30,
      kind: 'exercise',
      section: 'Block 3 — Round 1',
    },
    {
      id: 'b3-r2-jump-knee-tuck',
      exerciseId: 'jump-knee-tuck',
      name: 'Jump Knee Tuck',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knees to chest',
      section: 'Block 3 — Round 2',
    },
    {
      id: 'b3-r2-mary-katherine',
      exerciseId: 'mary-katherine',
      name: 'Mary Katherine (Jump Lunges)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Block 3 — Round 2',
    },
    {
      id: 'b3-r2-leapfrog-squats',
      exerciseId: 'leapfrog-squats',
      name: 'Leapfrog Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '2 forward, 2 back',
      section: 'Block 3 — Round 2',
    },
    {
      id: 'b3-r2-twist-combo-3way',
      exerciseId: 'twist-combo',
      name: 'Twist Combo — 3-way twist',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left-center-right',
      section: 'Block 3 — Round 2',
    },
    {
      id: 'b3-r2-twist-combo-180',
      exerciseId: 'twist-combo',
      name: 'Twist Combo — 180-degree twist',
      seconds: 30,
      kind: 'exercise',
      section: 'Block 3 — Round 2',
    },
    {
      id: 'b3-water',
      exerciseId: 'water-break-b3',
      name: 'Water Break',
      seconds: 30,
      kind: 'break',
      section: 'Block 3 — Round 2',
    },

    // ── Block 4 — R1 (5) + R2 (5) + Water (1) = 11 segments ────────────────
    // Rockstar Hops — flattened 15s facing left + 15s facing right (Q14)
    {
      id: 'b4-r1-rockstar-hops-l',
      exerciseId: 'rockstar-hops',
      name: 'Rockstar Hops — facing left',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'heels-to-butt hops',
      section: 'Block 4 — Round 1',
    },
    {
      id: 'b4-r1-rockstar-hops-r',
      exerciseId: 'rockstar-hops',
      name: 'Rockstar Hops — facing right',
      seconds: 15,
      kind: 'exercise',
      cue: 'heels-to-butt hops',
      section: 'Block 4 — Round 1',
    },
    {
      id: 'b4-r1-gap-jump',
      exerciseId: 'gap-jump',
      name: 'Gap Jump',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'long lateral jumps',
      section: 'Block 4 — Round 1',
    },
    {
      id: 'b4-r1-squat-jacks',
      exerciseId: 'squat-jacks',
      name: 'Squat Jacks',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hands behind head jacks, drop into low squat',
      section: 'Block 4 — Round 1',
    },
    {
      id: 'b4-r1-military-march',
      exerciseId: 'military-march',
      name: 'Military March',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'high-intensity marching, locking knees and elbows',
      section: 'Block 4 — Round 1',
    },
    {
      id: 'b4-r2-rockstar-hops-l',
      exerciseId: 'rockstar-hops',
      name: 'Rockstar Hops — facing left',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'heels-to-butt hops',
      section: 'Block 4 — Round 2',
    },
    {
      id: 'b4-r2-rockstar-hops-r',
      exerciseId: 'rockstar-hops',
      name: 'Rockstar Hops — facing right',
      seconds: 15,
      kind: 'exercise',
      cue: 'heels-to-butt hops',
      section: 'Block 4 — Round 2',
    },
    {
      id: 'b4-r2-gap-jump',
      exerciseId: 'gap-jump',
      name: 'Gap Jump',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'long lateral jumps',
      section: 'Block 4 — Round 2',
    },
    {
      id: 'b4-r2-squat-jacks',
      exerciseId: 'squat-jacks',
      name: 'Squat Jacks',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hands behind head jacks, drop into low squat',
      section: 'Block 4 — Round 2',
    },
    {
      id: 'b4-r2-military-march',
      exerciseId: 'military-march',
      name: 'Military March',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'high-intensity marching, locking knees and elbows',
      section: 'Block 4 — Round 2',
    },
    {
      id: 'b4-water',
      exerciseId: 'water-break-b4',
      name: 'Water Break',
      seconds: 30,
      kind: 'break',
      section: 'Block 4 — Round 2',
    },

    // ── Block 5 — R1 (5) + R2 (5) + Water (1) = 11 segments ────────────────
    {
      id: 'b5-r1-run-squat-180-jump-switch',
      exerciseId: 'run-squat-180-jump-switch',
      name: 'Run Squat 180 Jump Switch',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pivot jumps',
      section: 'Block 5 — Round 1',
    },
    {
      id: 'b5-r1-lateral-leapfrog-squats',
      exerciseId: 'lateral-leapfrog-squats',
      name: 'Lateral Leapfrog Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'side-to-side squat hops',
      section: 'Block 5 — Round 1',
    },
    {
      id: 'b5-r1-monster-truck-tires',
      exerciseId: 'monster-truck-tires',
      name: 'Monster Truck Tires',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'high-knee run 4 steps forward, 4 back',
      section: 'Block 5 — Round 1',
    },
    // Hot Foot — flattened 30s left + 30s right (Q14)
    {
      id: 'b5-r1-hot-foot-l',
      exerciseId: 'hot-foot',
      name: 'Hot Foot — left foot',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hopping in cross pattern',
      section: 'Block 5 — Round 1',
    },
    {
      id: 'b5-r1-hot-foot-r',
      exerciseId: 'hot-foot',
      name: 'Hot Foot — right foot',
      seconds: 30,
      kind: 'exercise',
      cue: 'hopping in cross pattern',
      section: 'Block 5 — Round 1',
    },
    {
      id: 'b5-r2-run-squat-180-jump-switch',
      exerciseId: 'run-squat-180-jump-switch',
      name: 'Run Squat 180 Jump Switch',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pivot jumps',
      section: 'Block 5 — Round 2',
    },
    {
      id: 'b5-r2-lateral-leapfrog-squats',
      exerciseId: 'lateral-leapfrog-squats',
      name: 'Lateral Leapfrog Squats',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'side-to-side squat hops',
      section: 'Block 5 — Round 2',
    },
    {
      id: 'b5-r2-monster-truck-tires',
      exerciseId: 'monster-truck-tires',
      name: 'Monster Truck Tires',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'high-knee run 4 steps forward, 4 back',
      section: 'Block 5 — Round 2',
    },
    {
      id: 'b5-r2-hot-foot-l',
      exerciseId: 'hot-foot',
      name: 'Hot Foot — left foot',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hopping in cross pattern',
      section: 'Block 5 — Round 2',
    },
    {
      id: 'b5-r2-hot-foot-r',
      exerciseId: 'hot-foot',
      name: 'Hot Foot — right foot',
      seconds: 30,
      kind: 'exercise',
      cue: 'hopping in cross pattern',
      section: 'Block 5 — Round 2',
    },
    {
      id: 'b5-water',
      exerciseId: 'water-break-b5',
      name: 'Water Break',
      seconds: 30,
      kind: 'break',
      section: 'Block 5 — Round 2',
    },

    // ── Sports Bonus Round (5 segments) ────────────────────────────────────
    // Pitch & Catch — flattened 30s right-arm + 30s left-arm (Q14)
    {
      id: 'bonus-pitch-catch-r',
      exerciseId: 'pitch-catch',
      name: 'Pitch & Catch — right-arm pitcher',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Sports Bonus Round',
    },
    {
      id: 'bonus-pitch-catch-l',
      exerciseId: 'pitch-catch',
      name: 'Pitch & Catch — left-arm pitcher',
      seconds: 30,
      kind: 'exercise',
      section: 'Sports Bonus Round',
    },
    // Jump Shot — flattened 30s catch-right/shoot-left + 30s catch-left/shoot-right (Q14)
    {
      id: 'bonus-jump-shot-r',
      exerciseId: 'jump-shot',
      name: 'Jump Shot — catch right / shoot left',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Sports Bonus Round',
    },
    {
      id: 'bonus-jump-shot-l',
      exerciseId: 'jump-shot',
      name: 'Jump Shot — catch left / shoot right',
      seconds: 30,
      kind: 'exercise',
      section: 'Sports Bonus Round',
    },
    {
      id: 'bonus-football-hero',
      exerciseId: 'football-hero',
      name: 'Football Hero',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: '4 lateral shuffles, 6 high-knee runs',
      section: 'Sports Bonus Round',
    },

    // ── Cool Down & Stretch (7 segments) ───────────────────────────────────
    {
      id: 'cd-jump-rope',
      exerciseId: 'jump-rope',
      name: 'Jump Rope (Low Impact Shake Out)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-marching-kick',
      exerciseId: 'marching-kick',
      name: 'Marching Kick',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-forward-bend',
      exerciseId: 'forward-bend-stretch',
      name: 'Forward Bend Stretch',
      seconds: 90,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-calf-stretch',
      exerciseId: 'calf-stretch',
      name: 'Calf Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating knee bends',
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-spine-stretch',
      exerciseId: 'spine-stretch',
      name: 'Spine Stretch (Cat/Cow)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    // Standing Quad Stretch — flattened R 30s + L 30s (Q14)
    {
      id: 'cd-quad-stretch-r',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — right',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down & Stretch',
    },
    {
      id: 'cd-quad-stretch-l',
      exerciseId: 'standing-quad-stretch',
      name: 'Standing Quad Stretch — left',
      seconds: 30,
      kind: 'exercise',
      section: 'Cool Down & Stretch',
    },
  ],
  loggedExerciseIds: [
    // Block 1
    'jump-squats',
    'run-stance-squats',
    'airborne-heisman',
    'swing-kicks',
    // Block 2
    'squat-reach-jump',
    'run-stance-squat-switch-pickup',
    'double-airborne-heisman',
    'circle-run',
    // Block 3
    'jump-knee-tuck',
    'mary-katherine',
    'leapfrog-squats',
    'twist-combo',
    // Block 4
    'rockstar-hops',
    'gap-jump',
    'squat-jacks',
    'military-march',
    // Block 5
    'run-squat-180-jump-switch',
    'lateral-leapfrog-squats',
    'monster-truck-tires',
    'hot-foot',
    // Sports Bonus Round
    'pitch-catch',
    'jump-shot',
    'football-hero',
  ],
}
