import type { PlayTimeline } from './types'

/**
 * P90X X Stretch authored play timeline — transcribed verbatim from
 * docs/requirements/x-stretch.md (the oracle). Order = play order.
 *
 * Locked decisions (see E18 spec §1 + §3):
 * - Sun Salutation Rounds 1–3 are multi-pose flows with no single total
 *   duration → `seconds: null`, no `reps`, the full chain verbatim in `cue`.
 *   The three rounds share `exerciseId: 'sun-salutation'` and run contiguous
 *   ("Continuous flow. Perform 3 complete rounds.") so they advance with a
 *   beep at each round switch but no get-ready gap between rounds.
 * - Q14 splits flatten a single doc item into consecutive segments sharing an
 *   `exerciseId`, seamless (no lead-in between halves): Spinal Twist → 15s L +
 *   15s R; Shoulder Circles → 4 × 20s phases. L/R items that the doc lists
 *   separately (Neck Stretch R/L, Side Stretch L/R, every glute/hamstring/quad
 *   pair) are distinct doc items → their own instances with distinct ids.
 * - Items marked `total` with internal cycles but no fixed sub-durations
 *   (Head Rolls 60s '6 cycles', Dreya Forearm 60s '2 cycles', Tapas 45s
 *   '3 cycles', Cat/Cow 60s '5 breathing cycles') stay ONE timed segment with
 *   the cycle text as `cue` — the doc gives no split durations; inventing them
 *   is prohibited.
 * - `leadIn: 5` on the first segment of every exercise instance except the
 *   timeline's first segment; none within splits; X Stretch has no breaks.
 * - GD-B: `loggedExerciseIds` is empty — a stretch session's completion status
 *   is the record; no per-move log.
 * - GD-C: the transcript cuts off at Child's Pose (Left); the final segment's
 *   `cue` appends `(transcript ends here)` and the workout ships verbatim.
 */
export const xStretch: PlayTimeline = {
  workoutKey: 'x-stretch',
  title: 'X Stretch',
  source: 'docs/requirements/x-stretch.md',
  segments: [
    // ── 1. Warm-Up (Sun Salutations) — 3 untimed flows (Done-to-advance) ────
    {
      id: 'sun-salutation-1',
      exerciseId: 'sun-salutation',
      name: 'Sun Salutation Round 1',
      seconds: null,
      kind: 'exercise',
      cue: 'Arms up -> Swan dive -> Flat back -> Plank -> Chaturanga -> Upward Dog -> Downward Dog (hold 30s) -> Jump to hands -> Flat back -> Forward Fold -> Reverse Swan Dive',
      section: 'Warm-Up (Sun Salutations)',
    },
    {
      id: 'sun-salutation-2',
      exerciseId: 'sun-salutation',
      name: 'Sun Salutation Round 2',
      seconds: null,
      kind: 'exercise',
      // Continuation of the sun-salutation instance (continuous flow): no lead-in.
      cue: 'Arms up -> Swan dive -> Flat back -> Plank -> Chaturanga -> Upward Dog -> Push-up -> Downward Dog (hold 15s) -> Jump to hands -> Flat back -> Forward Fold -> Reverse Swan Dive',
      section: 'Warm-Up (Sun Salutations)',
    },
    {
      id: 'sun-salutation-3',
      exerciseId: 'sun-salutation',
      name: 'Sun Salutation Round 3',
      seconds: null,
      kind: 'exercise',
      cue: 'Arms up -> Swan dive -> Flat back -> Plank -> Chaturanga -> Upward Dog -> Push-up -> Downward Dog (hold 15s) -> Jump to hands -> Flat back -> Forward Fold -> Reverse Swan Dive (tiptoe reach at top)',
      section: 'Warm-Up (Sun Salutations)',
    },

    // ── 2. Neck & Spine Mobilization (7 segments; Spinal Twist split 15L+15R)
    {
      id: 'neck-stretch-right',
      exerciseId: 'neck-stretch-right',
      name: 'Neck Stretch (Right wrist pull)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'ear to left shoulder; look up, look down, look forward',
      section: 'Neck & Spine Mobilization',
    },
    {
      id: 'neck-stretch-left',
      exerciseId: 'neck-stretch-left',
      name: 'Neck Stretch (Left wrist pull)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'ear to right shoulder; look up, look down, look forward',
      section: 'Neck & Spine Mobilization',
    },
    // Spinal Twist — one doc item, flattened 15s Left + 15s Right (Q14 split).
    {
      id: 'spinal-twist-left',
      exerciseId: 'spinal-twist',
      name: 'Spinal Twist (Backing up the car) — left',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'wide feet, torso rotation',
      section: 'Neck & Spine Mobilization',
    },
    {
      id: 'spinal-twist-right',
      exerciseId: 'spinal-twist',
      name: 'Spinal Twist (Backing up the car) — right',
      seconds: 15,
      kind: 'exercise',
      // Split continuation — seamless, no get-ready gap.
      cue: 'wide feet, torso rotation',
      section: 'Neck & Spine Mobilization',
    },
    // Head Rolls — one 60s timed segment; cycle text as cue (no invented split).
    {
      id: 'head-rolls',
      exerciseId: 'head-rolls',
      name: 'Head Rolls',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: '6 cycles, active hands pointing down',
      section: 'Neck & Spine Mobilization',
    },
    {
      id: 'expand-contract-chest-stretch',
      exerciseId: 'expand-contract-chest-stretch',
      name: 'Expand-Contract Chest Stretch',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'deep horse stance, pull arms wide',
      section: 'Neck & Spine Mobilization',
    },
    {
      id: 'tapas-stretch',
      exerciseId: 'tapas-stretch',
      name: 'Tapas Stretch',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: '3 cycles; horse stance, thumbs back, exhale forward',
      section: 'Neck & Spine Mobilization',
    },

    // ── 3. Wrist & Forearm Stretches (3 timed segments) ────────────────────
    {
      id: 'side-to-side-wrist-rocks',
      exerciseId: 'side-to-side-wrist-rocks',
      name: 'Side-to-Side Wrist Rocks',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '10 rock cycles left/right',
      section: 'Wrist & Forearm Stretches',
    },
    {
      id: 'fingertips-back-flexor-hold',
      exerciseId: 'fingertips-back-flexor-hold',
      name: 'Fingertips Back Flexor Hold',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'fingers point to knees, palms flat, shift weight back',
      section: 'Wrist & Forearm Stretches',
    },
    // Dreya Forearm — one 60s timed segment; cycle text as cue.
    {
      id: 'dreya-forearm-stretch',
      exerciseId: 'dreya-forearm-stretch',
      name: 'Dreya Forearm Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: '2 cycles; self-created tension pulling hands forward/back',
      section: 'Wrist & Forearm Stretches',
    },

    // ── 4. Upper Body Stretches (13 segments; Shoulder Circles split 4×20s)
    // Shoulder Circles — one doc item, flattened into 4 × 20s phases (Q14).
    {
      id: 'shoulder-circles-forward-medium',
      exerciseId: 'shoulder-circles',
      name: 'Shoulder Circles — forward medium',
      seconds: 20,
      kind: 'exercise',
      leadIn: 5,
      cue: 'forward medium',
      section: 'Upper Body Stretches',
    },
    {
      id: 'shoulder-circles-backward-medium',
      exerciseId: 'shoulder-circles',
      name: 'Shoulder Circles — backward medium',
      seconds: 20,
      kind: 'exercise',
      cue: 'backward medium',
      section: 'Upper Body Stretches',
    },
    {
      id: 'shoulder-circles-backward-big',
      exerciseId: 'shoulder-circles',
      name: 'Shoulder Circles — backward big',
      seconds: 20,
      kind: 'exercise',
      cue: 'backward big',
      section: 'Upper Body Stretches',
    },
    {
      id: 'shoulder-circles-forward-big',
      exerciseId: 'shoulder-circles',
      name: 'Shoulder Circles — forward big',
      seconds: 20,
      kind: 'exercise',
      cue: 'forward big',
      section: 'Upper Body Stretches',
    },
    {
      id: 'cross-body-arm-pull-right',
      exerciseId: 'cross-body-arm-pull-right',
      name: 'Cross-Body Arm Pull (Right)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Upper Body Stretches',
    },
    {
      id: 'overhead-triceps-pull-right',
      exerciseId: 'overhead-triceps-pull-right',
      name: 'Overhead Triceps Pull (Right)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Upper Body Stretches',
    },
    {
      id: 'cross-body-arm-pull-left',
      exerciseId: 'cross-body-arm-pull-left',
      name: 'Cross-Body Arm Pull (Left)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Upper Body Stretches',
    },
    {
      id: 'overhead-triceps-pull-left',
      exerciseId: 'overhead-triceps-pull-left',
      name: 'Overhead Triceps Pull (Left)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Upper Body Stretches',
    },
    {
      id: 'ballistic-huggers',
      exerciseId: 'ballistic-huggers',
      name: 'Ballistic Huggers (Chest Openers)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'alternating arm cross',
      section: 'Upper Body Stretches',
    },
    {
      id: 'wave-reachers',
      exerciseId: 'wave-reachers',
      name: 'Wave Reachers',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hands up, fold forward, sweep arms back',
      section: 'Upper Body Stretches',
    },
    {
      id: 'swimmers',
      exerciseId: 'swimmers',
      name: 'Swimmers (Backstroke/Front crawl)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '4 backstroke + 4 front crawl per arm',
      section: 'Upper Body Stretches',
    },
    {
      id: 'standing-side-stretch-left',
      exerciseId: 'standing-side-stretch-left',
      name: 'Standing Side Stretch (Left side bend)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left hand down, right arm over, right hip out',
      section: 'Upper Body Stretches',
    },
    {
      id: 'standing-side-stretch-right',
      exerciseId: 'standing-side-stretch-right',
      name: 'Standing Side Stretch (Right side bend)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right hand down, left arm over, left hip out',
      section: 'Upper Body Stretches',
    },

    // ── 5. Seated & Lying Core/Spine Stretches (8 timed segments) ──────────
    {
      id: 'spine-rollers',
      exerciseId: 'spine-rollers',
      name: 'Spine Rollers',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '10 rolls forward/back hugging knees to chest',
      section: 'Seated & Lying Core/Spine Stretches',
    },
    {
      id: 'shoulder-stand',
      exerciseId: 'shoulder-stand',
      name: 'Shoulder Stand',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'vertical leg balance, supporting lower back',
      section: 'Seated & Lying Core/Spine Stretches',
    },
    {
      id: 'plow-pose',
      exerciseId: 'plow-pose',
      name: 'Plow Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'feet drop overhead, hands clasped on floor',
      section: 'Seated & Lying Core/Spine Stretches',
    },
    {
      id: 'knees-to-ears',
      exerciseId: 'knees-to-ears',
      name: 'Knees to Ears',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knees bent next to ears from plow',
      section: 'Seated & Lying Core/Spine Stretches',
    },
    {
      id: 'vertebrae-roll-down',
      exerciseId: 'vertebrae-roll-down',
      name: 'Vertebrae Roll Down',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'slow roll out to back',
      section: 'Seated & Lying Core/Spine Stretches',
    },
    {
      id: 'seated-spinal-twist-right',
      exerciseId: 'seated-spinal-twist-right',
      name: 'Seated Spinal Twist (Right leg bent over)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pretzel leg, twist right; 5 deep breaths',
      section: 'Seated & Lying Core/Spine Stretches',
    },
    {
      id: 'seated-spinal-twist-left',
      exerciseId: 'seated-spinal-twist-left',
      name: 'Seated Spinal Twist (Left leg bent over)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pretzel leg, twist left; 5 deep breaths',
      section: 'Seated & Lying Core/Spine Stretches',
    },
    // Cat/Cow — one 60s timed segment; cycle text as cue.
    {
      id: 'cat-cow-stretch',
      exerciseId: 'cat-cow-stretch',
      name: 'Cat/Cow Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: '5 breathing cycles on hands and knees',
      section: 'Seated & Lying Core/Spine Stretches',
    },

    // ── 6. Seated Lower Body Stretches (13 timed segments) ─────────────────
    {
      id: 'seated-glute-stretch-right',
      exerciseId: 'seated-glute-stretch-right',
      name: 'Seated Glute Stretch (Right)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right ankle on left knee, pull left thigh/shin',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'seated-glute-stretch-left',
      exerciseId: 'seated-glute-stretch-left',
      name: 'Seated Glute Stretch (Left)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left ankle on right knee, pull right thigh/shin',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'standing-wide-leg-forward-fold',
      exerciseId: 'standing-wide-leg-forward-fold',
      name: 'Standing Wide-Leg Forward Fold',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'feet wide, parallel, folding arms',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'wide-fold-with-twist-right',
      exerciseId: 'wide-fold-with-twist-right',
      name: 'Wide Fold with Twist (Right arm up)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left hand down, right arm up',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'wide-fold-with-twist-left',
      exerciseId: 'wide-fold-with-twist-left',
      name: 'Wide Fold with Twist (Left arm up)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right hand down, left arm up',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'camel-pose',
      exerciseId: 'camel-pose',
      name: 'Camel Pose',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knees on floor, hips forward, arch back, hands to heels',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'cat-cow-counter',
      exerciseId: 'cat-cow-counter',
      name: 'Cat/Cow Counter',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '1 breathing cycle',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'hero-pose',
      exerciseId: 'hero-pose',
      name: 'Hero Pose',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'sitting between heels; hands, elbows, or flat on back',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'kenpo-quad-stretch-right',
      exerciseId: 'kenpo-quad-stretch-right',
      name: 'Kenpo Quad Stretch (Right knee forward)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pigeon stance, bend left knee, grab left foot',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'kenpo-quad-stretch-left',
      exerciseId: 'kenpo-quad-stretch-left',
      name: 'Kenpo Quad Stretch (Left knee forward)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pigeon stance, bend right knee, grab right foot',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'bow-pose',
      exerciseId: 'bow-pose',
      name: 'Bow Pose',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'lying on stomach, grab ankles, kick legs back to lift chest',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'low-prayer-squat',
      exerciseId: 'low-prayer-squat',
      name: 'Low Prayer Squat (Rocking)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'deep squat, elbows inside knees',
      section: 'Seated Lower Body Stretches',
    },
    {
      id: 'frog-stretch',
      exerciseId: 'frog-stretch',
      name: 'Frog Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'knees wide, feet out, hips push back',
      section: 'Seated Lower Body Stretches',
    },

    // ── 7. Hamstring & Calf Focus (6 timed segments) ───────────────────────
    {
      id: 'seated-single-leg-hamstring-left',
      exerciseId: 'seated-single-leg-hamstring-left',
      name: 'Seated Single-Leg Hamstring Stretch (Left straight)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right foot to inner thigh, fold forward',
      section: 'Hamstring & Calf Focus',
    },
    {
      id: 'seated-single-leg-hamstring-right',
      exerciseId: 'seated-single-leg-hamstring-right',
      name: 'Seated Single-Leg Hamstring Stretch (Right straight)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left foot to inner thigh, fold forward',
      section: 'Hamstring & Calf Focus',
    },
    {
      id: 'seated-two-leg-hamstring',
      exerciseId: 'seated-two-leg-hamstring',
      name: 'Seated Two-Leg Hamstring Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'both legs straight, feet flexed, fold forward',
      section: 'Hamstring & Calf Focus',
    },
    {
      id: 'ballistic-hamstring-stretch',
      exerciseId: 'ballistic-hamstring-stretch',
      name: 'Ballistic Hamstring Stretch',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'lying on back, 10 alternating straight leg lifts',
      section: 'Hamstring & Calf Focus',
    },
    {
      id: 'standing-split-leg-hamstring-right',
      exerciseId: 'standing-split-leg-hamstring-right',
      name: 'Standing Split-Leg Hamstring Stretch (Right forward)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pyramid pose, drive left hip down',
      section: 'Hamstring & Calf Focus',
    },
    {
      id: 'standing-split-leg-hamstring-left',
      exerciseId: 'standing-split-leg-hamstring-left',
      name: 'Standing Split-Leg Hamstring Stretch (Left forward)',
      seconds: 45,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pyramid pose, drive right hip down',
      section: 'Hamstring & Calf Focus',
    },

    // ── 8. Ankle, Calf & Feet Mobilization (6 timed segments) ──────────────
    {
      id: 'ankle-point-flex-right',
      exerciseId: 'ankle-point-flex-right',
      name: 'Ankle Point-Flex (Right)',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '8 reps',
      section: 'Ankle, Calf & Feet Mobilization',
    },
    {
      id: 'ankle-circles-right',
      exerciseId: 'ankle-circles-right',
      name: 'Ankle Circles Inward/Outward (Right)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '8 reps each',
      section: 'Ankle, Calf & Feet Mobilization',
    },
    {
      id: 'ankle-point-flex-left',
      exerciseId: 'ankle-point-flex-left',
      name: 'Ankle Point-Flex (Left)',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: '8 reps',
      section: 'Ankle, Calf & Feet Mobilization',
    },
    {
      id: 'ankle-circles-left',
      exerciseId: 'ankle-circles-left',
      name: 'Ankle Circles Inward/Outward (Left)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '8 reps each',
      section: 'Ankle, Calf & Feet Mobilization',
    },
    {
      id: 'downward-dog-calf-stretch',
      exerciseId: 'downward-dog-calf-stretch',
      name: 'Downward Dog (Alternating Calf Stretch)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'pedaling feet',
      section: 'Ankle, Calf & Feet Mobilization',
    },
    {
      id: 'upward-dog-ankle-stretch',
      exerciseId: 'upward-dog-ankle-stretch',
      name: 'Upward Dog with Ankle Stretch',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hip drop, chest up, feet wide and toes flat',
      section: 'Ankle, Calf & Feet Mobilization',
    },

    // ── 9. Cool Down (3 timed segments; transcript ends at the final one) ──
    {
      id: 'childs-pose-center',
      exerciseId: 'childs-pose-center',
      name: "Child's Pose (Center)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      section: 'Cool Down',
    },
    {
      id: 'childs-pose-right',
      exerciseId: 'childs-pose-right',
      name: "Child's Pose (Right side stretch)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hands side-walked right, left hand on top',
      section: 'Cool Down',
    },
    // GD-C: the transcript cuts off here — the cue appends an end-note.
    {
      id: 'childs-pose-left',
      exerciseId: 'childs-pose-left',
      name: "Child's Pose (Left side stretch)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hands side-walked left, right hand on top (transcript ends here)',
      section: 'Cool Down',
    },
  ],
  loggedExerciseIds: [],
}
