import type { PlayTimeline } from './types'

/**
 * P90X Yoga X (classic) authored play timeline — transcribed verbatim from
 * docs/requirements/yoga.md (Part 1, the oracle). Order = play order.
 *
 * Locked decisions (see E19 spec §1 + §3):
 * - Ranges are rounded to the nearest 15s midpoint, keeping the verbatim
 *   range in the cue (GD-D): Wide Forward Fold ~1-2 min -> 90s.
 * - Ashtanga Sun Salutations are 3 continuous untimed flows sharing
 *   'sun-salutation' exerciseId.
 * - Crescent, Warrior 1/2, Reverse Warrior, Triangle, and Twisting Triangle
 *   are transcribed as flows (seconds: null) with hold guidance in cue,
 *   as there is no sub-pose timed breakdown in the doc.
 * - Chair series holds have explicit timed segments. Water break is an optional
 *   wait flow (seconds: null).
 * - Knee-to-forehead core flows are flows (seconds: null). Right Angle series
 *   holds are timed (30s).
 * - GD-E classic cutoff: Prayer Twist in Lunge (Right leg) is the final segment,
 *   carrying the transcript cutoff cue.
 */
export const yogaClassic: PlayTimeline = {
  workoutKey: 'yoga-x',
  variant: 'classic',
  title: 'Yoga X (classic)',
  source: 'docs/requirements/yoga.md',
  segments: [
    // ── 1. Warm-Up & Prep Stretches (8 timed segments) ─────────────────────
    {
      id: 'mountain-pose-classic',
      exerciseId: 'mountain-pose-classic',
      name: 'Mountain Pose',
      seconds: 30,
      kind: 'exercise',
      cue: '5 deep breaths for mental focus',
      section: 'Warm-Up & Prep Stretches',
    },
    {
      id: 'wide-forward-fold-classic',
      exerciseId: 'wide-forward-fold-classic',
      name: 'Wide Forward Fold (Swan Dive)',
      seconds: 90, // GD-D midpoint of 1-2 min
      kind: 'exercise',
      leadIn: 5,
      cue: 'arms folded, hanging stretch (~1-2 min)',
      section: 'Warm-Up & Prep Stretches',
    },
    {
      id: 'wide-leg-twist-right-classic',
      exerciseId: 'wide-leg-twist-classic',
      name: 'Wide Leg Twist (Right arm up)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '5 breaths, left hand down/on block',
      section: 'Warm-Up & Prep Stretches',
    },
    {
      id: 'wide-leg-twist-left-classic',
      exerciseId: 'wide-leg-twist-classic',
      name: 'Wide Leg Twist (Left arm up)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: '5 breaths, right hand down/on block',
      section: 'Warm-Up & Prep Stretches',
    },
    {
      id: 'pyramid-hamstring-stretch-right-classic',
      exerciseId: 'pyramid-hamstring-stretch-classic',
      name: 'Pyramid Hamstring Stretch (Right leg forward)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      cue: 'hips squared, hands down',
      section: 'Warm-Up & Prep Stretches',
    },
    {
      id: 'pyramid-hamstring-stretch-left-classic',
      exerciseId: 'pyramid-hamstring-stretch-classic',
      name: 'Pyramid Hamstring Stretch (Left leg forward)',
      seconds: 60,
      kind: 'exercise',
      leadIn: 5,
      section: 'Warm-Up & Prep Stretches',
    },
    {
      id: 'standing-side-stretch-left-classic',
      exerciseId: 'standing-side-stretch-classic',
      name: 'Standing Side Stretch (Left side reach)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right hip kicked out, left hand down, right arm over',
      section: 'Warm-Up & Prep Stretches',
    },
    {
      id: 'standing-side-stretch-right-classic',
      exerciseId: 'standing-side-stretch-classic',
      name: 'Standing Side Stretch (Right side reach)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left hip kicked out, right hand down, left arm over',
      section: 'Warm-Up & Prep Stretches',
    },

    // ── 2. Ashtanga Sun Salutations (3 untimed flows) ──────────────────────
    {
      id: 'sun-salutation-1-classic',
      exerciseId: 'sun-salutation-classic',
      name: 'Vinyasa Cycle 1',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Inhale Arms Up -> Exhale Swan Dive -> Flat Back Inhale -> Step/Jump to Plank -> Chaturanga -> Upward Dog -> Downward Dog (hold ~30s) -> Jump to Hands -> Flat Back -> Forward Fold -> Reverse Swan Dive',
      section: 'Ashtanga Sun Salutations (Vinyasa Cycles)',
    },
    {
      id: 'sun-salutation-2-classic',
      exerciseId: 'sun-salutation-classic',
      name: 'Vinyasa Cycle 2',
      seconds: null,
      kind: 'exercise',
      cue: 'Inhale Arms Up -> Exhale Swan Dive -> Flat Back Inhale -> Step/Jump to Plank -> Chaturanga -> Upward Dog -> Downward Dog (hold ~30s) -> Jump to Hands -> Flat Back -> Forward Fold -> Reverse Swan Dive',
      section: 'Ashtanga Sun Salutations (Vinyasa Cycles)',
    },
    {
      id: 'sun-salutation-3-classic',
      exerciseId: 'sun-salutation-classic',
      name: 'Vinyasa Cycle 3',
      seconds: null,
      kind: 'exercise',
      cue: 'Inhale Arms Up -> Exhale Swan Dive -> Flat Back Inhale -> Step/Jump to Plank -> Chaturanga -> Upward Dog -> Downward Dog (hold ~30s) -> Jump to Hands -> Flat Back -> Forward Fold -> Reverse Swan Dive',
      section: 'Ashtanga Sun Salutations (Vinyasa Cycles)',
    },

    // ── 3. Vinyasa Flow - Runner\'s Series (2 timed segments) ───────────────
    {
      id: 'runners-pose-right-classic',
      exerciseId: 'runners-pose-classic',
      name: "Runner's Pose (Right leg forward)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa entry to Downward Dog -> Float right heel high -> Swing through to low lunge (fingertips touching) -> Lower to elbows (deep groin stretch); exit: Plank -> Vinyasa -> Downward Dog',
      section: "Vinyasa Flow - Runner's Series",
    },
    {
      id: 'runners-pose-left-classic',
      exerciseId: 'runners-pose-classic',
      name: "Runner's Pose (Left leg forward)",
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Float left heel high -> Swing through to low lunge -> Lower to elbows; exit: Plank -> Vinyasa -> Downward Dog',
      section: "Vinyasa Flow - Runner's Series",
    },

    // ── 4. Standing Pose Flow (Warrior Series) (12 untimed flows) ──────────
    {
      id: 'crescent-pose-right-classic',
      exerciseId: 'crescent-pose-classic',
      name: 'Crescent Pose (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa entry -> Right leg swing through -> Crescent Pose -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'crescent-pose-left-classic',
      exerciseId: 'crescent-pose-classic',
      name: 'Crescent Pose (Left leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Left leg swing through -> Crescent Pose -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'warrior-one-right-classic',
      exerciseId: 'warrior-one-classic',
      name: 'Warrior One (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Right leg swing through -> Warrior One (back heel down) -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'warrior-one-left-classic',
      exerciseId: 'warrior-one-classic',
      name: 'Warrior One (Left leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Left leg swing through -> Warrior One -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'warrior-two-right-classic',
      exerciseId: 'warrior-two-classic',
      name: 'Warrior Two (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Right leg swing through -> Warrior One -> Warrior Two -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'warrior-two-left-classic',
      exerciseId: 'warrior-two-classic',
      name: 'Warrior Two (Left leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Left leg swing through -> Warrior One -> Warrior Two -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'reverse-warrior-right-classic',
      exerciseId: 'reverse-warrior-classic',
      name: 'Reverse Warrior (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Right leg swing through -> Warrior One -> Warrior Two -> Reverse Warrior -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'reverse-warrior-left-classic',
      exerciseId: 'reverse-warrior-classic',
      name: 'Reverse Warrior (Left leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Left leg swing through -> Warrior One -> Warrior Two -> Reverse Warrior -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'triangle-pose-right-classic',
      exerciseId: 'triangle-pose-classic',
      name: 'Triangle Pose (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Right leg swing through -> Warrior One -> Warrior Two -> Reverse Warrior (straighten leg) -> Warrior Two -> Triangle Pose (reach left hip back, right hand to floor/block/leg, left arm up) -> Warrior Two -> Reverse Warrior -> Warrior Two -> Warrior One -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'triangle-pose-left-classic',
      exerciseId: 'triangle-pose-classic',
      name: 'Triangle Pose (Left leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Left leg swing through -> Warrior One -> Warrior Two -> Reverse Warrior (straighten leg) -> Warrior Two -> Triangle Pose -> Warrior Two -> Reverse Warrior -> Warrior Two -> Warrior One -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'twisting-triangle-right-classic',
      exerciseId: 'twisting-triangle-classic',
      name: 'Twisting Triangle (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Right leg swing through -> Warrior One -> Warrior Two -> Straighten leg -> Twisting Triangle (left hand to floor/block, right arm up) -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },
    {
      id: 'twisting-triangle-left-classic',
      exerciseId: 'twisting-triangle-classic',
      name: 'Twisting Triangle (Left leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Left leg swing through -> Warrior One -> Warrior Two -> Straighten leg -> Twisting Triangle (right hand to floor/block, left arm up) -> Vinyasa exit (~30-45s hold)',
      section: 'Standing Pose Flow (Warrior Series)',
    },

    // ── 5. Chair Pose Series (6 timed segments + 1 flow break) ─────────────
    {
      id: 'chair-pose-basic-classic',
      exerciseId: 'chair-pose-classic',
      name: 'Chair Pose (Basic)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'arms straight, hips dropped, feet/knees together',
      section: 'Chair Pose Series',
    },
    {
      id: 'tiptoe-balance-hold-1-classic',
      exerciseId: 'tiptoe-balance-hold-classic',
      name: 'Tiptoe Balance Hold',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'rise onto tiptoes in Chair Pose',
      section: 'Chair Pose Series',
    },
    {
      id: 'twisting-chair-left-classic',
      exerciseId: 'twisting-chair-classic',
      name: 'Twisting Chair Pose (Left twist)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left elbow outside right knee, hands in prayer',
      section: 'Chair Pose Series',
    },
    {
      id: 'tiptoe-balance-hold-2-classic',
      exerciseId: 'tiptoe-balance-hold-classic',
      name: 'Tiptoe Balance Hold',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'rise onto tiptoes in Chair Pose',
      section: 'Chair Pose Series',
    },
    {
      id: 'twisting-chair-right-classic',
      exerciseId: 'twisting-chair-classic',
      name: 'Twisting Chair Pose (Right twist)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right elbow outside left knee, hands in prayer',
      section: 'Chair Pose Series',
    },
    {
      id: 'tiptoe-balance-hold-3-classic',
      exerciseId: 'tiptoe-balance-hold-classic',
      name: 'Tiptoe Balance Hold',
      seconds: 15,
      kind: 'exercise',
      leadIn: 5,
      cue: 'rise onto tiptoes in Chair Pose',
      section: 'Chair Pose Series',
    },
    {
      id: 'optional-water-break-classic',
      exerciseId: 'optional-water-break-classic',
      name: 'Optional Brief Water Break',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Optional brief water break (untimed, skippable wait)',
      section: 'Chair Pose Series',
    },

    // ── 6. Vinyasa Flow - Knee-to-Forehead & Bound Angles (11 segments) ───
    {
      id: 'knee-to-forehead-core-flow-right-classic',
      exerciseId: 'knee-to-forehead-core-flow-classic',
      name: 'Knee-to-Forehead Core Flow (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Vinyasa entry to Downward Dog -> Float right heel high -> Knee-to-forehead tuck (3 times) -> Swing through to Warrior One -> Warrior Two -> Reverse Warrior -> Warrior Two',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'right-angle-pose-right-classic',
      exerciseId: 'right-angle-pose-classic',
      name: 'Right Angle Pose (Right leg)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right hand inside right foot, left arm up',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'extended-right-angle-pose-right-classic',
      exerciseId: 'extended-right-angle-pose-classic',
      name: 'Extended Right Angle Pose (Right leg)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'sweep left arm overhead, forming straight line from heel to fingers',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'bound-right-angle-right-classic',
      exerciseId: 'bound-right-angle-classic',
      name: 'Bound Right Angle / Half-Bind (Right leg)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'right arm under thigh, left hand behind back, clasp hands/wrist',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'exit-sequence-right-classic',
      exerciseId: 'exit-sequence-classic',
      name: 'Exit Sequence (Right side)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Warrior Two -> Reverse Warrior -> Warrior Two -> Warrior One -> Vinyasa exit',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'knee-to-forehead-core-flow-left-classic',
      exerciseId: 'knee-to-forehead-core-flow-classic',
      name: 'Knee-to-Forehead Core Flow (Left leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Float left heel high -> Knee-to-forehead tuck (3 times) -> Swing through to Warrior One -> Warrior Two -> Reverse Warrior -> Warrior Two',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'right-angle-pose-left-classic',
      exerciseId: 'right-angle-pose-classic',
      name: 'Right Angle Pose (Left leg)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left hand inside left foot, right arm up',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'extended-right-angle-pose-left-classic',
      exerciseId: 'extended-right-angle-pose-classic',
      name: 'Extended Right Angle Pose (Left leg)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'sweep right arm overhead, forming straight line from heel to fingers',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'bound-right-angle-left-classic',
      exerciseId: 'bound-right-angle-classic',
      name: 'Bound Right Angle / Half-Bind (Left leg)',
      seconds: 30,
      kind: 'exercise',
      leadIn: 5,
      cue: 'left arm under thigh, right hand behind back, clasp hands/wrist',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'exit-sequence-left-classic',
      exerciseId: 'exit-sequence-classic',
      name: 'Exit Sequence (Left side)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: 'Warrior Two -> Reverse Warrior -> Warrior Two -> Warrior One -> Vinyasa exit',
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
    {
      id: 'prayer-twist-in-lunge-right-classic',
      exerciseId: 'prayer-twist-in-lunge-classic',
      name: 'Prayer Twist in Lunge (Right leg)',
      seconds: null,
      kind: 'exercise',
      leadIn: 5,
      cue: "Float right heel high -> Swing through to Runner's Pose -> Prayer Twist (left elbow outside right knee, palms pressed) (transcript ends here — continue with the video)",
      section: 'Vinyasa Flow - Knee-to-Forehead & Bound Angles',
    },
  ],
  loggedExerciseIds: [],
}
